-- recreate_cron_and_all_functions_full_recursive.sql
-- Collected functions referenced (recursively) by public.sim_tick_v1
-- Generated by assistant. Review before executing.

-- ============================
-- Function: public.character_tick_jitter_seconds
-- ============================
CREATE OR REPLACE FUNCTION public.character_tick_jitter_seconds(p_character_id uuid)
 RETURNS integer
 LANGUAGE sql
 STABLE
AS $function$
  SELECT (abs(hashtext(p_character_id::text)) % 30)::int;
$function$;

-- ============================
-- Function: public.character_morning_depart_offset_minutes
-- ============================
CREATE OR REPLACE FUNCTION public.character_morning_depart_offset_minutes(p_character_id uuid, p_day integer, p_seed bigint)
 RETURNS integer
 LANGUAGE sql
 STABLE
AS $function$
  SELECT (abs(hashtext(p_seed::text || ':' || p_character_id::text || ':' || p_day::text)) % 121)::int;
$function$;

-- ============================
-- Function: public.world_time_minutes_of_day
-- ============================
CREATE OR REPLACE FUNCTION public.world_time_minutes_of_day(p_world_time timestamp with time zone)
 RETURNS integer
 LANGUAGE sql
 STABLE
AS $function$
  SELECT (EXTRACT(HOUR FROM p_world_time)::int * 60 + EXTRACT(MINUTE FROM p_world_time)::int);
$function$;

-- ============================
-- Function: public.world_day_number
-- ============================
CREATE OR REPLACE FUNCTION public.world_day_number(p_world_time timestamp with time zone)
 RETURNS integer
 LANGUAGE sql
 STABLE
AS $function$
  SELECT FLOOR(EXTRACT(EPOCH FROM (date_trunc('day', p_world_time) - timestamptz '2000-01-01 00:00:00+00')) / 86400)::int;
$function$;

-- ============================
-- Function: public.world_next_time_at
-- ============================
CREATE OR REPLACE FUNCTION public.world_next_time_at(p_world_time timestamp with time zone, p_hour integer, p_min integer)
 RETURNS timestamp with time zone
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  base_day timestamptz;
  target timestamptz;
BEGIN
  base_day := date_trunc('day', p_world_time);
  target := base_day + make_interval(hours => p_hour, mins => p_min);
  IF target <= p_world_time THEN
    target := target + interval '1 day';
  END IF;
  RETURN target;
END $function$;

-- ============================
-- Function: public.get_weather_for_biome_day_v1
-- ============================
CREATE OR REPLACE FUNCTION public.get_weather_for_biome_day_v1(p_biome_id integer, p_day integer, p_seed bigint)
 RETURNS TABLE(severity text, multiplier integer, blocked boolean)
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
  r int;
  b int;
BEGIN
  IF p_biome_id IS NULL THEN
    severity := 'light';
    multiplier := 1;
    blocked := false;
    RETURN NEXT;
    RETURN;
  END IF;

  r := abs(hashtext(p_seed::text || ':wx:' || p_biome_id::text || ':' || p_day::text)) % 100;

  IF r < 65 THEN
    severity := 'light';
    multiplier := 1;
    blocked := false;
  ELSIF r < 90 THEN
    severity := 'heavy';
    multiplier := 2;
    blocked := false;
  ELSE
    severity := 'severe';
    multiplier := 4;
    b := abs(hashtext(p_seed::text || ':blk:' || p_biome_id::text || ':' || p_day::text)) % 100;
    blocked := (b < 25);
  END IF;

  RETURN NEXT;
END $function$;

-- ============================
-- Function: public.maybe_create_camp_event_v1
-- ============================
CREATE OR REPLACE FUNCTION public.maybe_create_camp_event_v1(p_world_time timestamp with time zone, p_character_id uuid, p_reason text, p_severity text, p_biome_id integer, p_day integer, p_seed bigint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  roll int;
  threshold int;
BEGIN
  IF p_reason = 'night' THEN
    threshold := 8;
  ELSE
    threshold := 15;
  END IF;

  IF p_severity = 'severe' THEN
    threshold := GREATEST(threshold, 25);
  END IF;

  roll := abs(hashtext(
    p_seed::text || ':camp:' || p_character_id::text || ':' || p_day::text || ':' ||
    COALESCE(p_reason,'') || ':' || COALESCE(p_severity,'') || ':' || COALESCE(p_biome_id::text,'0')
  )) % 100;

  IF roll < threshold THEN
    INSERT INTO public.world_events (world_time, character_id, kind, severity, payload)
    VALUES (
      p_world_time,
      p_character_id,
      'camp_attack',
      p_severity,
      jsonb_build_object(
        'reason', p_reason,
        'biome_id', p_biome_id,
        'roll', roll,
        'threshold', threshold
      )
    );
  END IF;
END $function$;

-- ============================
-- Function: public.route_point_v1
-- ============================
CREATE OR REPLACE FUNCTION public.route_point_v1(p_route_id bigint, p_seq integer)
 RETURNS TABLE(x double precision, y double precision, location_id bigint, dwell_seconds double precision)
 LANGUAGE sql
 STABLE
AS $function$
  SELECT rp.x, rp.y, rp.location_id, rp.dwell_seconds
  FROM public.map_route_points rp
  WHERE rp.route_id = p_route_id AND rp.seq = p_seq
  LIMIT 1;
$function$;

-- ============================
-- Function: public.route_next_seq_v1
-- ============================
CREATE OR REPLACE FUNCTION public.route_next_seq_v1(p_route_id bigint, p_seq integer)
 RETURNS integer
 LANGUAGE plpgsql
 STABLE
AS $function$
declare
  v_is_loop boolean;
  v_next integer;
begin
  select coalesce(mr.is_loop, true)
    into v_is_loop
  from public.map_routes mr
  where mr.id = p_route_id;

  -- next available seq (gap-safe)
  select min(seq)
    into v_next
  from public.map_route_points
  where route_id = p_route_id
    and seq > p_seq;

  if v_next is not null then
    return v_next;
  end if;

  if v_is_loop then
    select min(seq)
      into v_next
    from public.map_route_points
    where route_id = p_route_id;

    return v_next;
  end if;

  -- non-loop: no next point
  return null;
end;
$function$;

-- ============================
-- Function: public.reroll_merchant_inventory_v2
-- ============================
CREATE OR REPLACE FUNCTION public.reroll_merchant_inventory_v2(p_merchant_id uuid, p_theme text DEFAULT 'general'::text, p_count integer DEFAULT NULL::integer)
 RETURNS TABLE(inserted_count integer, theme text, merchant_id uuid)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_theme text := COALESCE(NULLIF(p_theme, ''), 'general');
  v_total int;
  v_uncommon int;
  v_rare int;
  v_veryrare int;
  v_inserted int := 0;
  v_ins int;

  v_type text;
  v_is_admin boolean := false;
  v_uid uuid;
BEGIN
  -- Allow system calls (cron runs with auth.uid() NULL)
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    v_is_admin := true;
  ELSE
    SELECT (up.role = 'admin') INTO v_is_admin
    FROM public.user_profiles up
    WHERE up.id = v_uid;
  END IF;

  IF NOT COALESCE(v_is_admin, false) THEN
    RAISE EXCEPTION 'Only admins can reroll merchant stock';
  END IF;

  -- target count: default to 12-20
  v_total := COALESCE(p_count, 12 + floor(random() * 9)::int);
  IF v_total < 1 THEN v_total := 12; END IF;

  -- rarity distribution
  v_uncommon := GREATEST(0, round(v_total * 0.55)::int);
  v_rare := GREATEST(0, round(v_total * 0.35)::int);
  v_veryrare := GREATEST(0, v_total - v_uncommon - v_rare);
  v_inserted := 0;

  -- Clear existing stock
  DELETE FROM public.character_stock WHERE character_id = p_merchant_id;

  -- Ensure merchant profile row exists / update theme
  INSERT INTO public.merchant_profiles (merchant_id, theme)
  VALUES (p_merchant_id, v_theme)
  ON CONFLICT (merchant_id) DO UPDATE SET theme = EXCLUDED.theme;

  ---------------------------------------------------------------------------
  -- Insert helper: pick N items for a given rarity with theme match first,
  -- then fall back to general pool for any remaining.
  ---------------------------------------------------------------------------
  FOR v_type, v_ins IN
    SELECT 'Uncommon'::text, v_uncommon
    UNION ALL SELECT 'Rare'::text, v_rare
    UNION ALL SELECT 'Very Rare'::text, v_veryrare
  LOOP
    IF v_ins <= 0 THEN
      CONTINUE;
    END IF;

    -- Theme-first pass
    WITH candidates AS (
      SELECT id, payload
      FROM public.items_catalog
      WHERE (rarity = v_type)
        AND (
          v_theme = 'general'
          OR (merchant_tags IS NOT NULL AND merchant_tags @> ARRAY[v_theme])
        )
      ORDER BY random()
      LIMIT v_ins
    )
    INSERT INTO public.character_stock (character_id, item_id, qty, card_payload, price_cp, notes)
    SELECT
      p_merchant_id,
      (payload->>'item_id')::text,
      1,
      payload,
      COALESCE((payload->>'value_cp')::int, (payload->>'price_cp')::int, 0),
      'auto_reroll:' || v_theme
    FROM candidates;

    GET DIAGNOSTICS v_ins = ROW_COUNT;
    v_inserted := v_inserted + v_ins;

    -- Fill remaining from general pool
    IF v_ins < (SELECT CASE v_type WHEN 'Uncommon' THEN v_uncommon WHEN 'Rare' THEN v_rare ELSE v_veryrare END) THEN
      WITH fill AS (
        SELECT payload
        FROM public.items_catalog
        WHERE (rarity = v_type)
          AND NOT EXISTS (
            SELECT 1
            FROM public.character_stock cs
            WHERE cs.character_id = p_merchant_id
              AND cs.item_id = (public.items_catalog.payload->>'item_id')::text
          )
        ORDER BY random()
        LIMIT ((SELECT CASE v_type WHEN 'Uncommon' THEN v_uncommon WHEN 'Rare' THEN v_rare ELSE v_veryrare END) - v_ins)
      )
      INSERT INTO public.character_stock (character_id, item_id, qty, card_payload, price_cp, notes)
      SELECT
        p_merchant_id,
        (payload->>'item_id')::text,
        1,
        payload,
        COALESCE((payload->>'value_cp')::int, (payload->>'price_cp')::int, 0),
        'auto_reroll:fallback_general'
      FROM fill;

      GET DIAGNOSTICS v_ins = ROW_COUNT;
      v_inserted := v_inserted + v_ins;
    END IF;
  END LOOP;

  -- Safety: ensure not empty
  IF NOT EXISTS (SELECT 1 FROM public.character_stock WHERE character_id = p_merchant_id) THEN
    WITH safety AS (
      SELECT payload
      FROM public.items_catalog
      WHERE rarity IN ('Uncommon','Rare')
      ORDER BY random()
      LIMIT v_total
    )
    INSERT INTO public.character_stock (character_id, item_id, qty, card_payload, price_cp, notes)
    SELECT
      p_merchant_id,
      (payload->>'item_id')::text,
      1,
      payload,
      COALESCE((payload->>'value_cp')::int, (payload->>'price_cp')::int, 0),
      'auto_reroll:safety'
    FROM safety;

    GET DIAGNOSTICS v_ins = ROW_COUNT;
    v_inserted := v_inserted + v_ins;
  END IF;

  RETURN QUERY SELECT v_inserted, v_theme, p_merchant_id;
END;
$function$;

-- ============================
-- Function: public.advance_world_time_v1
-- ============================
CREATE OR REPLACE FUNCTION public.advance_world_time_v1()
 RETURNS world_state
 LANGUAGE plpgsql
AS $function$
DECLARE
  ws public.world_state;
  real_delta_seconds double precision;
  game_delta interval;
BEGIN
  SELECT * INTO ws FROM public.world_state WHERE id = 1 FOR UPDATE;

  real_delta_seconds := GREATEST(0, EXTRACT(EPOCH FROM (now() - ws.updated_at)));
  game_delta := make_interval(secs => real_delta_seconds * ws.time_scale);

  UPDATE public.world_state
  SET world_time = ws.world_time + game_delta,
      updated_at = now()
  WHERE id = 1
  RETURNING * INTO ws;

  RETURN ws;
END $function$;

-- ============================
-- Function: public.advance_all_characters_v3 (wrapper)
-- ============================
CREATE OR REPLACE FUNCTION public.advance_all_characters_v3()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  perform public.advance_all_characters_v3(timezone('utc', now()));
end;
$function$;

-- ============================
-- Function: public.advance_all_characters_v3(p_world_time)
-- (Full implementation)
-- ============================
CREATE OR REPLACE FUNCTION public.advance_all_characters_v3(p_world_time timestamp with time zone)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  c record;

  tod_min int;
  is_night boolean;
  is_evening_depart_window boolean;

  ws_seed bigint;
  day_num int;

  -- route points
  ax double precision; ay double precision; aloc bigint; adwell double precision;
  bx double precision; by_ double precision; bloc bigint; bdwell double precision;

  dist double precision;
  speed_units_per_hour numeric;
  travel_seconds_base double precision;
  travel_seconds double precision;

  -- weather
  biome_id int;
  wx_severity text;
  wx_mult int;
  wx_blocked boolean;

  -- progress
  seg_total double precision;
  seg_elapsed double precision;
  t double precision;

  -- dwell
  dwell_seconds_effective double precision;

  -- scheduling
  jitter int;
  next_morning timestamptz;
  depart_offset_min int;

  -- route progression
  v_next_seq integer;

  -- camp pause
  remaining_seconds double precision;

  -- merchant reroll chance
  reroll_roll int;
BEGIN
-- ------------------------------------------------------------
-- PRE-PASS) Repair invalid movers (prevents stuck 'moving' with null seq/timestamps)
-- ------------------------------------------------------------
UPDATE public.characters
SET state = 'resting',
    location_id = COALESCE(last_known_location_id, location_id),
    projected_destination_id = NULL,
    segment_started_at = NULL,
    segment_ends_at = NULL,
    route_segment_progress = 0,
    next_action_at = p_world_time + interval '10 minutes' + make_interval(secs => public.character_tick_jitter_seconds(id))
WHERE is_hidden = false
  AND state IN ('moving','excursion')
  AND (
    route_id IS NULL
    OR current_point_seq IS NULL
    OR next_point_seq IS NULL
    OR segment_started_at IS NULL
    OR segment_ends_at IS NULL
    OR segment_ends_at <= segment_started_at
  );

  -- Load world seed if present, otherwise fall back to 1337
  SELECT COALESCE(seed, 1337) INTO ws_seed
  FROM public.world_state
  WHERE id = 1;

  day_num := public.world_day_number(p_world_time);
  tod_min := public.world_time_minutes_of_day(p_world_time);

  is_night := (tod_min >= 20*60) OR (tod_min < 6*60);
  is_evening_depart_window := (tod_min >= 18*60) AND (tod_min < 20*60);

  -- Process characters that are due. Skip hidden characters.
  FOR c IN
    SELECT *
    FROM public.characters
    WHERE is_hidden = false
      AND state <> 'hidden'
      AND (next_action_at IS NULL OR next_action_at <= p_world_time)
    FOR UPDATE SKIP LOCKED
  LOOP
    -- deterministic jitter (0..29 seconds) stored for reference
    jitter := public.character_tick_jitter_seconds(c.id);

    -- If next_action_at is null, initialize it to "now + jitter" and skip this tick.
    IF c.next_action_at IS NULL THEN
      UPDATE public.characters
      SET next_action_at = p_world_time + make_interval(secs => jitter),
          tick_jitter_seconds = jitter
      WHERE id = c.id;
      CONTINUE;
    END IF;

    -- ------------------------------------------------------------
    -- A) Handle camping state (resume when allowed)
    -- ------------------------------------------------------------
    IF c.state = 'camping' THEN
      -- Determine biome for weather gating (use last_known_location if available)
      SELECT l.biome_id INTO biome_id
      FROM public.locations l
      WHERE l.id = COALESCE(c.last_known_location_id, c.location_id);

      SELECT severity, multiplier, blocked
      INTO wx_severity, wx_mult, wx_blocked
      FROM public.get_weather_for_biome_day_v1(biome_id, day_num, ws_seed)
      LIMIT 1;

      -- Resume only during travel hours AND when not weather-blocked (if camp_reason is weather)
      IF (NOT is_night) AND (COALESCE(c.camp_reason,'') <> 'weather' OR wx_blocked = false) THEN
        remaining_seconds := COALESCE(c.paused_remaining_seconds, 0);

        -- apply current weather multiplier to remaining duration
        travel_seconds := remaining_seconds * GREATEST(1, COALESCE(wx_mult, 1));

        UPDATE public.characters
        SET state = COALESCE(c.paused_state, 'moving'),
            paused_state = NULL,
            paused_remaining_seconds = NULL,
            camp_reason = NULL,
            camp_started_at = NULL,
            segment_started_at = p_world_time,
            segment_ends_at = p_world_time + make_interval(secs => travel_seconds),
            next_action_at = p_world_time + make_interval(secs => GREATEST(10, jitter)) -- small stagger
        WHERE id = c.id;

      ELSE
        -- stay camping; check again in ~1 minute of world time
        UPDATE public.characters
        SET next_action_at = p_world_time + interval '1 minute' + make_interval(secs => jitter)
        WHERE id = c.id;
      END IF;

      CONTINUE;
    END IF;

    -- ------------------------------------------------------------
    -- B) If it's night and character is currently moving/excursion, force camp
    -- ------------------------------------------------------------
    IF is_night AND c.state IN ('moving','excursion') THEN
      -- compute remaining seconds on segment, clamp >= 0
      remaining_seconds := GREATEST(0, EXTRACT(EPOCH FROM (COALESCE(c.segment_ends_at, p_world_time) - p_world_time)));

      -- create deterministic camp event chance (night)
      SELECT l.biome_id INTO biome_id
      FROM public.locations l
      WHERE l.id = COALESCE(c.last_known_location_id, c.location_id);

      PERFORM public.maybe_create_camp_event_v1(p_world_time, c.id, 'night', 'light', biome_id, day_num, ws_seed);

      UPDATE public.characters
      SET paused_state = c.state,
          paused_remaining_seconds = remaining_seconds::int,
          state = 'camping',
          camp_reason = 'night',
          camp_started_at = p_world_time,
          location_id = NULL, -- ensure sprite-only state
          next_action_at = public.world_next_time_at(p_world_time, 6, 0) + make_interval(secs => jitter)
      WHERE id = c.id;

      CONTINUE;
    END IF;

    -- ------------------------------------------------------------
    -- C) If resting at a location and in 18:00–20:00, delay departure to 06:00–08:00
    -- ------------------------------------------------------------
    IF c.state = 'resting' AND c.location_id IS NOT NULL AND is_evening_depart_window THEN
      depart_offset_min := public.character_morning_depart_offset_minutes(c.id, day_num + 1, ws_seed); -- 0..120
      next_morning := public.world_next_time_at(p_world_time, 6, 0) + make_interval(mins => depart_offset_min);

      UPDATE public.characters
      SET next_action_at = next_morning,
          tick_jitter_seconds = jitter
      WHERE id = c.id;

      CONTINUE;
    END IF;

    -- ------------------------------------------------------------
    -- D) Resting at location: dwell until dwell_ends_at, then depart
    -- ------------------------------------------------------------
    IF c.state = 'resting' AND c.location_id IS NOT NULL THEN
      -- If dwell_ends_at is in the future, just wait.
      IF c.dwell_ends_at IS NOT NULL AND c.dwell_ends_at > p_world_time THEN
        UPDATE public.characters
        SET next_action_at = LEAST(c.dwell_ends_at, p_world_time + interval '30 minutes') + make_interval(secs => jitter),
            tick_jitter_seconds = jitter
        WHERE id = c.id;
        CONTINUE;
      END IF;

      -- Ensure route assigned
      IF c.route_id IS NULL THEN
        UPDATE public.characters
        SET next_action_at = p_world_time + interval '6 hours' + make_interval(secs => jitter)
        WHERE id = c.id;
        CONTINUE;
      END IF;

      -- Determine current seq (fallback to route_point_seq/current_point_seq)
      IF c.current_point_seq IS NULL THEN
        UPDATE public.characters
        SET current_point_seq = COALESCE(c.route_point_seq, 1)
        WHERE id = c.id;
        c.current_point_seq := COALESCE(c.route_point_seq, 1);
      END IF;

      c.next_point_seq := public.route_next_seq_v1(c.route_id, c.current_point_seq);

-- If no next point (end of a non-loop route), stop routing and remain resting here.
IF c.next_point_seq IS NULL THEN
  UPDATE public.characters
  SET route_id = NULL,
      current_point_seq = NULL,
      next_point_seq = NULL,
      projected_destination_id = NULL,
      segment_started_at = NULL,
      segment_ends_at = NULL,
      route_segment_progress = 0,
      next_action_at = p_world_time + interval '24 hours' + make_interval(secs => jitter)
  WHERE id = c.id;
  CONTINUE;
END IF;

      -- Pull A and B points
      SELECT x,y,location_id,dwell_seconds INTO ax,ay,aloc,adwell
      FROM public.route_point_v1(c.route_id, c.current_point_seq);

      SELECT x,y,location_id,dwell_seconds INTO bx,by_,bloc,bdwell
      FROM public.route_point_v1(c.route_id, c.next_point_seq);

      IF ax IS NULL OR bx IS NULL THEN
        UPDATE public.characters
        SET next_action_at = p_world_time + interval '6 hours' + make_interval(secs => jitter)
        WHERE id = c.id;
        CONTINUE;
      END IF;

      -- Weather for biome of current location (resting at location)
      SELECT l.biome_id INTO biome_id
      FROM public.locations l
      WHERE l.id = c.location_id;

      SELECT severity, multiplier, blocked
      INTO wx_severity, wx_mult, wx_blocked
      FROM public.get_weather_for_biome_day_v1(biome_id, day_num, ws_seed)
      LIMIT 1;

      IF wx_blocked THEN
        -- Weather blocks travel: camp in-place (sprite on map) even though at location.
        -- Invariant says: if in location list => no sprite. So we remove location_id and camp.
        PERFORM public.maybe_create_camp_event_v1(p_world_time, c.id, 'weather', wx_severity, biome_id, day_num, ws_seed);

        UPDATE public.characters
        SET paused_state = 'resting',
            paused_remaining_seconds = 0,
            state = 'camping',
            camp_reason = 'weather',
            camp_started_at = p_world_time,
            location_id = NULL,
            last_known_location_id = c.location_id,
            next_action_at = p_world_time + interval '30 minutes' + make_interval(secs => jitter)
        WHERE id = c.id;

        CONTINUE;
      END IF;

      -- Compute travel duration
      dist := sqrt( (bx-ax)*(bx-ax) + (by_-ay)*(by_-ay) );
      speed_units_per_hour := COALESCE(c.move_speed_units_per_hour, 1.0);
      travel_seconds_base := CASE
        WHEN speed_units_per_hour <= 0 THEN 3600
        ELSE (dist / speed_units_per_hour::double precision) * 3600.0
      END;

      travel_seconds := travel_seconds_base * GREATEST(1, COALESCE(wx_mult, 1));

      UPDATE public.characters
      SET state = CASE WHEN c.route_mode = 'excursion' THEN 'excursion' ELSE 'moving' END,
          location_id = NULL,
          last_known_location_id = c.location_id,
          projected_destination_id = bloc,
          current_point_seq = c.current_point_seq,
          next_point_seq = c.next_point_seq,
          segment_started_at = p_world_time,
          segment_ends_at = p_world_time + make_interval(secs => travel_seconds),
          route_segment_progress = 0,
          next_action_at = p_world_time + interval '1 minute' + make_interval(secs => jitter),
          tick_jitter_seconds = jitter
      WHERE id = c.id;

      CONTINUE;
    END IF;

    -- ------------------------------------------------------------
    -- E) Moving/excursion: update progress; handle arrival; handle weather blocks
    -- ------------------------------------------------------------
    IF c.state IN ('moving','excursion') THEN
      -- Ensure route
      IF c.route_id IS NULL OR c.current_point_seq IS NULL OR c.next_point_seq IS NULL THEN
        UPDATE public.characters
        SET state = 'resting',
            projected_destination_id = NULL,
            location_id = COALESCE(c.last_known_location_id, c.location_id),
            next_action_at = p_world_time + interval '6 hours' + make_interval(secs => jitter)
        WHERE id = c.id;
        CONTINUE;
      END IF;

      -- Load points
      SELECT x,y,location_id,dwell_seconds INTO ax,ay,aloc,adwell
      FROM public.route_point_v1(c.route_id, c.current_point_seq);

      SELECT x,y,location_id,dwell_seconds INTO bx,by_,bloc,bdwell
      FROM public.route_point_v1(c.route_id, c.next_point_seq);

      IF ax IS NULL OR bx IS NULL THEN
        UPDATE public.characters
        SET state = 'resting',
            projected_destination_id = NULL,
            location_id = COALESCE(c.last_known_location_id, c.location_id),
            next_action_at = p_world_time + interval '6 hours' + make_interval(secs => jitter)
        WHERE id = c.id;
        CONTINUE;
      END IF;

      -- Weather based on last_known_location biome
      SELECT l.biome_id INTO biome_id
      FROM public.locations l
      WHERE l.id = COALESCE(c.last_known_location_id, c.location_id);

      SELECT severity, multiplier, blocked
      INTO wx_severity, wx_mult, wx_blocked
      FROM public.get_weather_for_biome_day_v1(biome_id, day_num, ws_seed)
      LIMIT 1;

      IF wx_blocked THEN
        remaining_seconds := GREATEST(0, EXTRACT(EPOCH FROM (COALESCE(c.segment_ends_at, p_world_time) - p_world_time)));

        PERFORM public.maybe_create_camp_event_v1(p_world_time, c.id, 'weather', wx_severity, biome_id, day_num, ws_seed);

        UPDATE public.characters
        SET paused_state = c.state,
            paused_remaining_seconds = remaining_seconds::int,
            state = 'camping',
            camp_reason = 'weather',
            camp_started_at = p_world_time,
            location_id = NULL,
            next_action_at = p_world_time + interval '30 minutes' + make_interval(secs => jitter)
        WHERE id = c.id;

        CONTINUE;
      END IF;

      -- If arrived
      IF c.segment_ends_at IS NOT NULL AND c.segment_ends_at <= p_world_time THEN
        -- Compute next seq (NULL means end of non-loop route)
        v_next_seq := public.route_next_seq_v1(c.route_id, c.next_point_seq);

        -- Snap to B
        UPDATE public.characters
        SET x = bx,
            y = by_,
            route_segment_progress = 1,
            current_point_seq = c.next_point_seq,
            next_point_seq = v_next_seq,
            last_known_location_id = COALESCE(bloc, c.last_known_location_id),
            projected_destination_id = NULL,
            segment_started_at = NULL,
            segment_ends_at = NULL
        WHERE id = c.id;

        -- If B is a stop (location_id not null), enter resting/dwell
        IF bloc IS NOT NULL THEN
          dwell_seconds_effective :=
            CASE
              WHEN COALESCE(bdwell, 0) > 0 THEN bdwell
              ELSE (COALESCE(c.dwell_hours, 6) * 3600)::double precision
            END;

          -- Merchant inventory reroll: 35% on town stop; 100% if returning from excursion
          IF c.kind = 'merchant' THEN
            reroll_roll := abs(hashtext(ws_seed::text || ':reroll:' || c.id::text || ':' || day_num::text || ':' || bloc::text)) % 100;

            IF c.state = 'excursion' OR reroll_roll < 35 THEN
              BEGIN
                PERFORM public.reroll_merchant_inventory_v2(c.id);
              EXCEPTION WHEN undefined_function THEN
                NULL;
              END;
            END IF;
          END IF;

          UPDATE public.characters
          SET state = 'resting',
              -- End-of-route (non-loop): clear route so we don't attempt to depart again
              route_id = CASE WHEN v_next_seq IS NULL THEN NULL ELSE c.route_id END,
              current_point_seq = CASE WHEN v_next_seq IS NULL THEN NULL ELSE c.next_point_seq END,
              next_point_seq = CASE WHEN v_next_seq IS NULL THEN NULL ELSE v_next_seq END,
              location_id = bloc,
              projected_destination_id = NULL,
              dwell_started_at = p_world_time,
              dwell_ends_at = p_world_time + make_interval(secs => dwell_seconds_effective),
              next_action_at = p_world_time + make_interval(secs => dwell_seconds_effective) + make_interval(secs => jitter)
          WHERE id = c.id;

          CONTINUE;
        END IF;

-- If route ended on a non-stop point, camp here and clear routing.
IF bloc IS NULL AND v_next_seq IS NULL THEN
  UPDATE public.characters
  SET state = 'camping',
      camp_reason = 'route_end',
      camp_started_at = p_world_time,
      route_id = NULL,
      current_point_seq = NULL,
      next_point_seq = NULL,
      projected_destination_id = NULL,
      segment_started_at = NULL,
      segment_ends_at = NULL,
      route_segment_progress = 1,
      location_id = NULL,
      next_action_at = public.world_next_time_at(p_world_time, 6, 0) + make_interval(secs => jitter)
  WHERE id = c.id;

  CONTINUE;
END IF;

        -- If B is not a stop, immediately start next segment (subject to night window)
        IF is_night THEN
          remaining_seconds := 0;
          UPDATE public.characters
          SET paused_state = 'moving',
              paused_remaining_seconds = remaining_seconds::int,
              state = 'camping',
              camp_reason = 'night',
              camp_started_at = p_world_time,
              location_id = NULL,
              next_action_at = public.world_next_time_at(p_world_time, 6, 0) + make_interval(secs => jitter)
          WHERE id = c.id;

          CONTINUE;
        END IF;

        -- schedule next action soon to start the next segment
        UPDATE public.characters
        SET next_action_at = p_world_time + interval '5 seconds' + make_interval(secs => jitter)
        WHERE id = c.id;

        CONTINUE;
      END IF;

      -- Not arrived yet: update progress and x/y
      seg_total := GREATEST(1, EXTRACT(EPOCH FROM (COALESCE(c.segment_ends_at, p_world_time) - COALESCE(c.segment_started_at, p_world_time))));
      seg_elapsed := GREATEST(0, EXTRACT(EPOCH FROM (p_world_time - COALESCE(c.segment_started_at, p_world_time))));
      t := LEAST(1, seg_elapsed / seg_total);

      UPDATE public.characters
      SET x = ax + (bx - ax) * t,
          y = ay + (by_ - ay) * t,
          route_segment_progress = t,
          last_moved_at = timezone('utc', now()),
          next_action_at = p_world_time + interval '1 minute' + make_interval(secs => jitter),
          tick_jitter_seconds = jitter
      WHERE id = c.id;

      CONTINUE;
    END IF;

    -- ------------------------------------------------------------
    -- F) Default catch-all: re-check later
    -- ------------------------------------------------------------
    UPDATE public.characters
    SET next_action_at = p_world_time + interval '10 minutes' + make_interval(secs => jitter),
        tick_jitter_seconds = jitter
    WHERE id = c.id;

  END LOOP;
END;

$function$;

-- ============================
-- Function: public.sim_tick_v1
-- ============================
CREATE OR REPLACE FUNCTION public.sim_tick_v1()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  ws public.world_state;
  last_ts timestamptz;
  real_delta_seconds double precision;
BEGIN
  -- Only one tick at a time
  IF NOT pg_try_advisory_lock(987654321) THEN
    RETURN;
  END IF;

  -- Gate: only allow one "real tick" about once per minute
  SELECT updated_at INTO last_ts
  FROM public.world_state
  WHERE id = 1;

  real_delta_seconds := EXTRACT(EPOCH FROM (now() - COALESCE(last_ts, now())));

  IF real_delta_seconds < 50 THEN
    PERFORM pg_advisory_unlock(987654321);
    RETURN;
  END IF;

  ws := public.advance_world_time_v1();

  BEGIN
    PERFORM public.advance_all_characters_v3(ws.world_time);
  EXCEPTION WHEN undefined_function THEN
    NULL_