export default function NpcForgeClassGuideStyles() {
  return <style jsx global>{`
    .npc-forge-class-guide{
      --class-accent:168,108,255;
      --class-secondary:88,214,199;
      --class-warm:218,159,88;
      position:relative;
      gap:8px!important;
      padding:8px!important;
      background:
        radial-gradient(circle at 78% 7%,rgba(var(--class-accent),.1),transparent 27%),
        radial-gradient(circle at 13% 78%,rgba(var(--class-secondary),.045),transparent 30%),
        linear-gradient(160deg,rgba(12,12,22,.995),rgba(5,8,15,.998))!important;
    }
    .npc-forge-class-guide.is-class-artificer{--class-accent:170,92,255;--class-secondary:74,211,226;--class-warm:220,161,83}
    .npc-forge-class-guide__view-header{position:absolute;top:10px;right:12px;z-index:12;display:block!important;margin:0!important;padding:0!important;border:0!important;background:transparent!important;box-shadow:none!important}
    .npc-forge-class-guide__tabs{display:flex;justify-content:flex-end;gap:6px;padding:3px;border:1px solid rgba(var(--class-accent),.18);border-radius:9px;background:rgba(5,8,16,.76);backdrop-filter:blur(8px)}
    .npc-forge-class-guide__tabs button,.npc-forge-class-guide__subhead-actions button,.npc-forge-class-guide__subclass-confirm button{padding:7px 11px;border:1px solid rgba(255,255,255,.14);border-radius:6px;color:rgba(255,255,255,.78);background:rgba(255,255,255,.025);font-size:.66rem;font-weight:800}
    .npc-forge-class-guide__tabs button.is-active,.npc-forge-class-guide__subclass-confirm button.is-primary{border-color:rgba(var(--class-accent),.84);color:#fff;background:linear-gradient(180deg,rgba(var(--class-accent),.56),rgba(56,34,92,.8));box-shadow:0 0 18px rgba(var(--class-accent),.11)}
    .npc-forge-class-guide__overview-book{position:relative;padding:0!important;overflow:hidden;border:1px solid rgba(var(--class-accent),.22)!important;border-radius:12px!important;background:linear-gradient(150deg,rgba(12,17,29,.985),rgba(5,10,18,.995))!important;box-shadow:inset 0 1px rgba(255,255,255,.02),0 14px 34px rgba(0,0,0,.22)!important}
    .npc-forge-class-guide__overview-book::before{content:"";position:absolute;inset:6px;z-index:0;pointer-events:none;border:1px solid rgba(var(--class-accent),.055);border-radius:9px}
    .npc-forge-class-guide__overview-book>*{position:relative;z-index:1}
    .npc-forge-class-guide__book-hero{position:relative;display:grid!important;grid-template-columns:minmax(0,58%) minmax(310px,42%)!important;min-height:218px!important;overflow:hidden;border-bottom:1px solid rgba(var(--class-accent),.2)!important;background:linear-gradient(105deg,rgba(7,11,20,.995),rgba(13,14,26,.94) 55%,rgba(7,10,18,.35))!important}
    .npc-forge-class-guide__book-hero::before{content:"";position:absolute;inset:0;z-index:1;pointer-events:none;background:radial-gradient(circle at 76% 48%,rgba(var(--class-secondary),.11),transparent 25%),linear-gradient(90deg,rgba(5,8,15,.18),transparent 52%,rgba(5,8,15,.08))}
    .npc-forge-class-guide__book-hero::after{content:"";position:absolute;left:0;right:0;bottom:0;z-index:3;height:1px;background:linear-gradient(90deg,transparent,rgba(var(--class-accent),.55),rgba(var(--class-secondary),.34),transparent)}
    .npc-forge-class-guide__hero-copy{position:relative;z-index:4;display:grid;align-content:center;gap:8px;padding:22px 22px 18px 24px}
    .npc-forge-class-guide__hero-kicker{display:flex;align-items:center;gap:7px;font-size:.54rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase}
    .npc-forge-class-guide__hero-kicker span{color:#d9b5ff}.npc-forge-class-guide__hero-kicker em{padding:2px 6px;border:1px solid rgba(var(--class-accent),.16);border-radius:999px;color:rgba(255,255,255,.42);font-style:normal;letter-spacing:.035em}
    .npc-forge-class-guide__book-hero h2{margin:0!important;color:#f7f0e6!important;font-family:Georgia,"Times New Roman",serif;font-size:clamp(2rem,3vw,3rem)!important;font-weight:500!important;letter-spacing:.035em;line-height:.98!important;text-shadow:0 4px 20px rgba(0,0,0,.52)}
    .npc-forge-class-guide__hero-tagline{max-width:58ch;margin:0!important;color:#eee2cf!important;font-family:Georgia,"Times New Roman",serif;font-size:.82rem!important;line-height:1.45!important}
    .npc-forge-class-guide__hero-art{position:relative;z-index:0;min-width:0;overflow:hidden;background:#090d15}
    .npc-forge-class-guide__hero-art::before{content:"";position:absolute;inset:0;z-index:2;pointer-events:none;background:linear-gradient(90deg,rgba(8,11,19,.99) 0%,rgba(8,11,19,.66) 15%,rgba(8,11,19,.1) 48%,rgba(8,11,19,.12)),linear-gradient(0deg,rgba(5,8,14,.46),transparent 48%)}
    .npc-forge-class-guide__hero-art img{display:block;width:100%;height:100%;min-height:218px!important;object-fit:cover!important;object-position:center 28%!important;filter:saturate(.9) contrast(1.06) brightness(.82);transform:scale(1.12)}
    .npc-forge-class-guide.is-class-artificer .npc-forge-class-guide__hero-art img{object-position:center 25%!important;filter:saturate(1.02) contrast(1.08) brightness(.86)}
    .npc-forge-class-guide__hero-facts{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:6px!important;max-width:620px;margin-top:5px!important}
    .npc-forge-class-guide__hero-facts>div{position:relative;display:grid!important;gap:2px!important;min-height:47px;padding:8px 9px 8px 30px!important;border:1px solid rgba(var(--class-accent),.17)!important;border-radius:7px!important;background:linear-gradient(145deg,rgba(25,22,39,.58),rgba(7,12,21,.74))!important;box-shadow:inset 0 1px rgba(255,255,255,.02)!important}
    .npc-forge-class-guide__hero-facts>div::before{content:"✦";position:absolute;left:9px;top:50%;transform:translateY(-50%);display:grid;place-items:center;width:15px;height:15px;border:1px solid rgba(var(--class-accent),.38);border-radius:50%;color:rgb(var(--class-secondary));background:rgba(var(--class-secondary),.045);font-size:.5rem}
    .npc-forge-class-guide__hero-facts span{color:rgba(255,255,255,.45)!important;font-size:.46rem!important;font-weight:800!important;letter-spacing:.065em!important;text-transform:uppercase}.npc-forge-class-guide__hero-facts strong{color:#fff!important;font-size:.62rem!important;line-height:1.28!important}
    .npc-forge-class-guide__overview-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(300px,34%);gap:14px;padding:12px 14px 14px}
    .npc-forge-class-guide__overview-main{display:grid;align-content:start;gap:10px;min-width:0}
    .npc-forge-class-guide__dock-lane{position:relative;min-width:0;min-height:625px;border-radius:12px;background:radial-gradient(circle at 50% 18%,rgba(var(--class-accent),.025),transparent 42%)}
    .npc-forge-class-guide__dock-lane>span{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}
    .npc-forge-class-guide__overview-copy{padding:2px 3px 0}.npc-forge-class-guide__overview-copy p{max-width:86ch;margin:0;color:rgba(245,238,226,.86);font-family:Georgia,"Times New Roman",serif;font-size:.73rem;line-height:1.5}
    .npc-forge-class-guide__detailed-controls{display:grid;gap:10px;padding:14px clamp(1rem,2.5vw,2rem) 0}
    .npc-forge-class-guide__subclasses{display:grid;gap:8px;padding:12px;border:1px solid rgba(var(--class-accent),.19);border-radius:10px;background:linear-gradient(145deg,rgba(23,21,37,.66),rgba(7,13,23,.8));box-shadow:inset 0 1px rgba(255,255,255,.015)}
    .npc-forge-class-guide__subclasses.is-compact{padding:0;border:0;border-radius:0;background:transparent;box-shadow:none}
    .npc-forge-class-guide__subclasses.is-required.is-compact{padding:7px 8px;border:1px solid rgba(255,121,121,.28);border-radius:8px;background:rgba(76,24,39,.07)}
    .npc-forge-class-guide__subclasses.is-required:not(.is-compact){border-color:rgba(255,121,121,.46)}
    .npc-forge-class-guide__subhead{display:flex;align-items:end;justify-content:space-between;gap:12px;padding-bottom:6px;border-bottom:1px solid rgba(var(--class-accent),.14)}.npc-forge-class-guide__subhead>div:first-child{display:flex;align-items:baseline;gap:9px;min-width:0}.npc-forge-class-guide__subhead span{color:#d4a8ff;font-family:Georgia,"Times New Roman",serif;font-size:.79rem;font-weight:600;letter-spacing:.035em;text-transform:uppercase}.npc-forge-class-guide__subhead strong{overflow:hidden;color:rgba(255,255,255,.53);font-size:.55rem;font-weight:650;text-overflow:ellipsis;white-space:nowrap}.npc-forge-class-guide__subhead-actions{display:flex;align-items:center;gap:7px}.npc-forge-class-guide__subhead-actions label,.npc-forge-class-guide__subclasses>p{color:rgba(255,255,255,.58);font-size:.59rem}
    .npc-forge-class-guide__subclass-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;position:relative}
    .npc-forge-class-guide__subclass-grid>button,.npc-forge-class-guide__subclass-more>div>button{display:flex;align-items:center;gap:6px;min-width:0;min-height:38px;padding:6px 7px;border:1px solid rgba(255,255,255,.1);border-radius:7px;color:rgba(255,255,255,.77);background:linear-gradient(145deg,rgba(13,17,27,.94),rgba(7,12,20,.98));text-align:left;transition:border-color .15s ease,background .15s ease,box-shadow .15s ease,transform .15s ease}
    .npc-forge-class-guide__subclass-grid>button:hover,.npc-forge-class-guide__subclass-grid>button:focus-visible,.npc-forge-class-guide__subclass-more>div>button:hover,.npc-forge-class-guide__subclass-more>div>button:focus-visible{border-color:rgba(var(--class-secondary),.48);background:linear-gradient(145deg,rgba(15,37,44,.42),rgba(11,17,28,.98));outline:none;transform:translateY(-1px)}
    .npc-forge-class-guide__subclass-grid>button.is-active,.npc-forge-class-guide__subclass-more>div>button.is-active{border-color:rgba(var(--class-accent),.78);background:linear-gradient(145deg,rgba(var(--class-accent),.18),rgba(9,16,27,.98));box-shadow:inset 2px 0 rgba(var(--class-accent),.85),0 0 14px rgba(var(--class-accent),.07)}
    .npc-forge-class-guide__subclass-grid>button.is-selected,.npc-forge-class-guide__subclass-more>div>button.is-selected{box-shadow:inset 2px 0 rgb(var(--class-secondary)),0 0 14px rgba(var(--class-secondary),.07)}
    .npc-forge-class-guide__subclass-mark{flex:0 0 auto;display:grid;place-items:center;width:21px;height:21px;border:1px solid rgba(var(--class-accent),.3);border-radius:50%;color:rgb(var(--class-secondary));background:rgba(var(--class-accent),.06);font-size:.59rem}
    .npc-forge-class-guide__subclass-label{display:grid;min-width:0;gap:1px}.npc-forge-class-guide__subclass-label strong{overflow:hidden;color:#f2eaf9;font-family:Georgia,"Times New Roman",serif;font-size:.6rem;font-weight:600;line-height:1.2;text-overflow:ellipsis;white-space:nowrap}.npc-forge-class-guide__subclass-label small{overflow:hidden;color:rgba(255,255,255,.38);font-size:.42rem;line-height:1.2;text-overflow:ellipsis;white-space:nowrap}
    .npc-forge-class-guide__subclass-more{position:relative;min-width:0}.npc-forge-class-guide__subclass-more>summary{display:flex;align-items:center;justify-content:center;gap:5px;min-height:38px;padding:6px 7px;border:1px solid rgba(var(--class-secondary),.22);border-radius:7px;color:#9cece2;background:rgba(7,17,25,.86);cursor:pointer;list-style:none}.npc-forge-class-guide__subclass-more>summary::-webkit-details-marker{display:none}.npc-forge-class-guide__subclass-more>summary span{font-size:.8rem}.npc-forge-class-guide__subclass-more>summary strong{font-family:Georgia,"Times New Roman",serif;font-size:.6rem;font-weight:600}.npc-forge-class-guide__subclass-more>summary small{display:none}.npc-forge-class-guide__subclass-more[open]>summary{border-color:rgba(var(--class-secondary),.5);background:rgba(14,41,49,.74)}
    .npc-forge-class-guide__subclass-more>div{position:absolute;right:0;top:calc(100% + 6px);z-index:20;display:grid;grid-template-columns:repeat(2,minmax(130px,1fr));gap:6px;width:min(430px,72vw);padding:8px;border:1px solid rgba(var(--class-accent),.32);border-radius:9px;background:rgba(8,12,21,.99);box-shadow:0 16px 36px rgba(0,0,0,.48)}
    .npc-forge-class-guide__subclass-confirm{display:flex;align-items:center;justify-content:space-between;gap:9px;min-height:26px}.npc-forge-class-guide__subclass-confirm>span{color:rgba(255,255,255,.5);font-size:.55rem}.npc-forge-class-guide__subclass-confirm button{padding:5px 8px;font-size:.54rem}.npc-forge-class-guide__subclass-confirm button:disabled{opacity:.45;cursor:not-allowed}.npc-forge-class-guide__requirement,.npc-forge-class-guide__subclass-level-note{margin:0!important;color:rgba(255,214,214,.72)!important;font-size:.52rem!important}.npc-forge-class-guide__subclass-level-note{color:rgba(255,255,255,.43)!important}
    .npc-forge-class-guide__compare-drawer{border-top:1px solid rgba(255,255,255,.08);padding-top:7px}.npc-forge-class-guide__compare-drawer summary{color:#d8c4f8;cursor:pointer;font-size:.65rem;font-weight:800}.npc-forge-class-guide__compare-drawer>div{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:8px}.npc-forge-class-guide__compare-drawer button{display:grid;gap:4px;padding:9px;border:1px solid rgba(255,255,255,.1);border-radius:8px;color:#fff;background:rgba(255,255,255,.025);text-align:left}.npc-forge-class-guide__compare-drawer button.is-active{border-color:rgb(var(--class-accent));background:rgba(var(--class-accent),.15)}.npc-forge-class-guide__compare-drawer small,.npc-forge-class-guide__compare-drawer span{color:rgba(255,255,255,.63);font-size:.61rem;line-height:1.4}
    .npc-forge-class-guide__choice-routing{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:10px;padding:9px 11px;border:1px solid rgba(var(--class-secondary),.18);border-radius:8px;background:linear-gradient(90deg,rgba(var(--class-secondary),.05),rgba(6,12,21,.5));box-shadow:inset 0 1px rgba(255,255,255,.015)}
    .npc-forge-class-guide__choice-routing.is-compact{grid-template-columns:auto minmax(0,1fr);gap:9px;min-height:42px;padding:7px 10px;border-color:rgba(var(--class-secondary),.2);background:rgba(6,14,23,.48)}
    .npc-forge-class-guide__choice-routing-icon{display:grid;place-items:center;width:30px;height:30px;border:1px solid rgba(var(--class-accent),.32);border-radius:50%;color:#bdeff0;background:radial-gradient(circle,rgba(var(--class-accent),.13),rgba(7,11,20,.68));font-family:Georgia,"Times New Roman",serif;font-size:.78rem;font-weight:700}.npc-forge-class-guide__choice-routing>div:nth-child(2){display:grid;gap:2px}.npc-forge-class-guide__choice-routing>div:nth-child(2)>span{color:rgb(var(--class-secondary));font-size:.51rem;font-weight:900;letter-spacing:.09em;text-transform:uppercase}.npc-forge-class-guide__choice-routing>div:nth-child(2)>strong{color:#d9eef0;font-size:.61rem;line-height:1.35}.npc-forge-class-guide__choice-routing>div:nth-child(2)>small{color:rgba(255,255,255,.53);font-size:.53rem;line-height:1.4}
    .npc-forge-class-guide__choice-routing.is-compact>div:nth-child(2)>strong{color:#9fc7ca;font-family:Georgia,"Times New Roman",serif;font-size:.6rem;font-weight:500}
    .npc-forge-class-guide__choice-routing-counts{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:5px}.npc-forge-class-guide__choice-routing-counts span{padding:4px 7px;border:1px solid rgba(var(--class-secondary),.11);border-radius:999px;color:#d8fff9;background:rgba(var(--class-secondary),.055);font-size:.52rem}.npc-forge-class-guide__choice-routing-counts b{color:#fff}
    .npc-forge-class-guide__section-title{display:flex;align-items:end;justify-content:space-between;gap:10px;padding:2px 2px 7px;border-bottom:1px solid rgba(var(--class-accent),.14)}.npc-forge-class-guide__section-title>span{color:#d4a8ff;font-family:Georgia,"Times New Roman",serif;font-size:.78rem;letter-spacing:.04em;text-transform:uppercase}.npc-forge-class-guide__section-title>small{color:rgba(255,255,255,.4);font-size:.49rem}
    .npc-forge-class-guide__table-card{display:grid;gap:6px;max-height:493px;padding:8px!important;overflow:auto!important;border:1px solid rgba(var(--class-accent),.18)!important;border-radius:8px!important;background:rgba(5,10,18,.72)!important;box-shadow:inset 0 1px rgba(255,255,255,.012)!important}
    .npc-forge-class-guide__table-card .class-level-guide__row{grid-template-columns:48px 48px minmax(185px,1.7fr) 58px 82px minmax(90px,.8fr)!important;min-height:31px!important}
    .npc-forge-class-guide__table-card .class-level-guide__row>div{padding:5px 6px!important;font-size:.53rem!important;line-height:1.25!important}.npc-forge-class-guide__table-card .class-level-guide__row.is-head{position:sticky;top:0;z-index:2;min-height:34px!important;background:linear-gradient(180deg,rgba(28,21,40,.99),rgba(13,16,28,.99))!important}.npc-forge-class-guide__table-card .class-level-guide__row.is-current{background:rgba(var(--class-accent),.07)!important;box-shadow:inset 3px 0 rgb(var(--class-secondary))}.npc-forge-class-guide__table-card .class-level-guide__features button{padding:0 2px!important;border:0;color:#eee3d4;background:transparent;text-align:left;text-decoration:none;font-family:Georgia,"Times New Roman",serif;font-size:.53rem}.npc-forge-class-guide__table-card .class-level-guide__features button:hover,.npc-forge-class-guide__table-card .class-level-guide__features button:focus-visible{color:#8fe6df;text-decoration:underline;text-underline-offset:2px;outline:none}
    .npc-forge-class-guide__table-footnote{display:flex;align-items:center;gap:7px;padding:6px 4px 1px;color:rgba(255,255,255,.48)}.npc-forge-class-guide__table-footnote>span{display:grid;place-items:center;width:17px;height:17px;border:1px solid rgba(var(--class-accent),.35);border-radius:50%;color:#d5b7ff;font-family:Georgia,"Times New Roman",serif;font-size:.52rem;font-weight:700}.npc-forge-class-guide__table-footnote p{margin:0;font-size:.5rem;line-height:1.35}
    .npc-forge-class-guide__detail{min-height:130px}.npc-forge-class-guide__detail p,.npc-forge-class-guide__subclass-intro p,.npc-forge-class-guide .class-book-guide__feature p{color:rgba(255,255,255,.82)!important;font-size:.82rem!important;line-height:1.68!important}
    .npc-forge-class-guide__level-heading{margin-bottom:12px;padding:10px 12px;border:1px solid rgba(var(--class-accent),.3);border-radius:9px;background:linear-gradient(90deg,rgba(var(--class-accent),.12),rgba(var(--class-secondary),.03))}.npc-forge-class-guide__level-heading h3{margin-bottom:0}.npc-forge-class-guide .class-book-guide__levels>section{padding-top:1.25rem!important}.npc-forge-class-guide .class-book-guide__feature h4{font-size:1rem}.npc-forge-class-guide .class-book-guide__outline{top:0}.npc-forge-class-guide__warning,.npc-forge-class-guide__loading{padding:9px;border-radius:8px;color:#ffd5a2;background:rgba(132,73,24,.16)}.npc-forge-class-guide__footer-note{margin:0!important;padding:6px 8px!important;border:0!important;color:rgba(255,255,255,.34)!important;background:transparent!important;font-size:.48rem!important}
    body .npc-forge-class-feature-dock{border:1px solid rgba(182,116,255,.9)!important;border-radius:15px!important;background:radial-gradient(circle at 84% 14%,rgba(74,211,226,.075),transparent 26%),radial-gradient(circle at 18% 82%,rgba(170,92,255,.1),transparent 34%),linear-gradient(155deg,rgba(18,14,31,.995),rgba(6,11,21,.998) 58%,rgba(6,16,24,.995))!important;box-shadow:inset 0 0 0 1px rgba(255,255,255,.02),inset 0 0 34px rgba(119,68,183,.07),0 24px 72px rgba(0,0,0,.62),0 0 0 3px rgba(69,41,99,.22),0 0 42px rgba(126,72,199,.14)!important}
    body .npc-forge-class-feature-dock.is-viewport-floating{max-height:min(76dvh,calc(100dvh - var(--npc-forge-class-dock-top,112px) - 12px))!important}
    body .npc-forge-class-feature-dock.is-viewport-floating.has-feature{min-height:min(540px,calc(100dvh - var(--npc-forge-class-dock-top,112px) - 14px))}
    body .npc-forge-class-feature-dock::before{content:"";position:absolute;inset:6px;z-index:0;pointer-events:none;border:1px solid rgba(177,123,255,.11);border-radius:10px;background:linear-gradient(135deg,rgba(255,255,255,.01),transparent 28%,transparent 72%,rgba(74,211,226,.015))}
    body .npc-forge-class-feature-dock::after{content:"✦";position:absolute;left:50%;top:-12px;z-index:5;transform:translateX(-50%);display:grid;place-items:center;width:28px;height:24px;border:1px solid rgba(182,116,255,.7);border-radius:50%;color:#a7f3f3;background:radial-gradient(circle,rgba(170,92,255,.52),rgba(20,14,34,.99) 68%);box-shadow:0 0 18px rgba(170,92,255,.36);font-size:.65rem}
    body .npc-forge-class-feature-dock__head,body .npc-forge-class-feature-dock__body{position:relative;z-index:2}
    body .npc-forge-class-feature-dock__head{padding:15px 15px 12px!important;border-bottom:1px solid rgba(182,116,255,.2)!important;background:linear-gradient(180deg,rgba(38,24,56,.97),rgba(12,16,28,.97))!important}
    body .npc-forge-class-feature-dock__title-group{justify-items:center;flex:1;text-align:center}.npc-forge-class-feature-dock__title-group>span{color:#d9a9ff!important;font-family:Georgia,"Times New Roman",serif;font-size:.53rem!important;letter-spacing:.12em!important}.npc-forge-class-feature-dock__title-group>h3{color:#8ce8e4!important;font-family:Georgia,"Times New Roman",serif;font-size:1.08rem!important;font-weight:500!important;letter-spacing:.025em!important;text-shadow:0 3px 14px rgba(0,0,0,.35)}
    body .npc-forge-class-feature-dock__head-actions{position:absolute;right:12px;top:11px}.npc-forge-class-feature-dock__head-actions>em{display:none}.npc-forge-class-feature-dock__head-actions>button{min-width:38px!important;height:25px!important;padding:0 7px!important;border-color:rgba(182,116,255,.42)!important;border-radius:7px!important;background:rgba(8,10,18,.76)!important;font-size:.49rem!important}
    body .npc-forge-class-feature-dock__body{gap:12px!important;padding:14px 16px 17px!important;background-image:radial-gradient(circle at 84% 62%,rgba(170,92,255,.035),transparent 28%),linear-gradient(rgba(255,255,255,.009) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.007) 1px,transparent 1px);background-size:auto,34px 34px,34px 34px}
    body .npc-forge-class-feature-dock__class-chip{justify-self:center;border-color:rgba(74,211,226,.22)!important;color:#c9fbf7!important;background:rgba(74,211,226,.045)!important}
    body .npc-forge-class-feature-dock__summary{padding:2px 1px;color:rgba(245,238,226,.87)!important}
    body .npc-forge-class-feature-dock__summary .class-feature-text,body .npc-forge-class-feature-dock__summary p{font-family:Georgia,"Times New Roman",serif;font-size:.73rem!important;line-height:1.58!important}
    body .npc-forge-class-feature-dock__summary li{font-family:Georgia,"Times New Roman",serif;font-size:.7rem!important;line-height:1.55!important}body .npc-forge-class-feature-dock__summary li::marker{color:#56d7df}
    body .npc-forge-class-feature-dock__highlights{padding:10px 11px!important;border:1px solid rgba(182,116,255,.18)!important;border-left:3px solid rgba(74,211,226,.68)!important;border-radius:9px!important;background:linear-gradient(90deg,rgba(74,211,226,.045),rgba(170,92,255,.035))!important}
    body .npc-forge-class-feature-dock__highlights>strong{color:#cdb2ff!important;font-size:.51rem!important;letter-spacing:.09em!important}.npc-forge-class-feature-dock__meta{justify-content:center!important}.npc-forge-class-feature-dock__meta>span{border-color:rgba(182,116,255,.13)!important;background:rgba(9,12,21,.52)!important}
    body .npc-forge-class-feature-dock__routing-note{margin-top:auto!important;border-color:rgba(220,161,83,.18)!important;border-left-color:#dca153!important;color:rgba(237,214,197,.72)!important;background:linear-gradient(90deg,rgba(92,52,27,.13),rgba(8,14,25,.38))!important}.npc-forge-class-feature-dock__listed-note{border-color:rgba(182,116,255,.19)!important;border-left-color:#b674ff!important;background:linear-gradient(90deg,rgba(105,55,160,.12),rgba(8,14,25,.4))!important}.npc-forge-class-feature-dock__drag-cue{color:rgba(255,255,255,.37)!important}.npc-forge-class-feature-dock__drag-cue span{color:#78e7df!important}
    @media(max-width:1180px){.npc-forge-class-guide__overview-layout{grid-template-columns:minmax(0,1fr) minmax(280px,32%)}.npc-forge-class-guide__book-hero{grid-template-columns:minmax(0,57%) minmax(280px,43%)!important}.npc-forge-class-guide__subclass-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.npc-forge-class-guide__subclass-more>div{grid-template-columns:1fr;width:280px}.npc-forge-class-guide__table-card .class-level-guide__row{grid-template-columns:43px 43px minmax(150px,1.6fr) 52px 72px minmax(80px,.8fr)!important}}
    @media(max-width:900px){.npc-forge-class-guide{padding:8px!important}.npc-forge-class-guide__view-header{position:static;display:flex!important;justify-content:flex-end;margin-bottom:2px!important}.npc-forge-class-guide__book-hero{grid-template-columns:1fr!important}.npc-forge-class-guide__hero-art{min-height:210px;order:-1}.npc-forge-class-guide__hero-art img{min-height:210px!important}.npc-forge-class-guide__hero-art::before{background:linear-gradient(0deg,rgba(8,11,19,.99),transparent 56%)}.npc-forge-class-guide__hero-copy{padding:18px}.npc-forge-class-guide__hero-facts{grid-template-columns:repeat(3,minmax(0,1fr))!important}.npc-forge-class-guide__overview-layout{grid-template-columns:1fr;padding:10px}.npc-forge-class-guide__dock-lane{display:none}.npc-forge-class-guide__choice-routing{grid-template-columns:auto 1fr}.npc-forge-class-guide__choice-routing-counts{grid-column:2;justify-content:flex-start}.npc-forge-class-guide__compare-drawer>div{grid-template-columns:1fr}.npc-forge-class-guide__table-card .class-level-guide__row{grid-template-columns:45px 45px minmax(180px,1.6fr) 55px 82px minmax(90px,.8fr)!important}}
    @media(max-width:760px){.npc-forge-class-guide__tabs{width:100%}.npc-forge-class-guide__tabs button{flex:1}.npc-forge-class-guide__hero-facts{grid-template-columns:1fr!important}.npc-forge-class-guide__subhead{align-items:stretch;flex-direction:column}.npc-forge-class-guide__subhead>div:first-child{display:grid;gap:2px}.npc-forge-class-guide__subhead-actions{justify-content:space-between}.npc-forge-class-guide__subclass-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.npc-forge-class-guide__subclass-more>div{left:0;right:auto;width:min(300px,82vw)}.npc-forge-class-guide__subclass-confirm{align-items:stretch;flex-direction:column}.npc-forge-class-guide__choice-routing{grid-template-columns:1fr}.npc-forge-class-guide__choice-routing-icon{display:none}.npc-forge-class-guide__choice-routing-counts{grid-column:auto}.npc-forge-class-guide__section-title{align-items:flex-start;flex-direction:column}.npc-forge-class-guide__table-card{overflow-x:auto!important}.npc-forge-class-guide__table-card .class-level-guide__table{min-width:620px}}
  `}</style>;
}