export default function NpcForgeClassGuideStyles() {
  return <style jsx global>{`
    .npc-forge-class-guide{
      --class-accent:168,108,255;
      --class-secondary:88,214,199;
      --class-warm:218,159,88;
      gap:14px!important;
      padding:14px!important;
      background:
        radial-gradient(circle at 76% 8%,rgba(var(--class-accent),.11),transparent 28%),
        radial-gradient(circle at 14% 76%,rgba(var(--class-secondary),.055),transparent 30%),
        linear-gradient(160deg,rgba(15,13,26,.99),rgba(5,8,15,.995))!important;
    }
    .npc-forge-class-guide.is-class-artificer{--class-accent:170,92,255;--class-secondary:74,211,226;--class-warm:220,161,83}
    .npc-forge-class-guide__view-header{margin:0!important;align-items:center!important;border:1px solid rgba(var(--class-accent),.28)!important;border-radius:12px!important;background:linear-gradient(145deg,rgba(35,24,51,.78),rgba(11,14,25,.94))!important;box-shadow:inset 0 1px rgba(255,255,255,.035),0 12px 28px rgba(0,0,0,.16)!important}
    .npc-forge-class-guide__tabs{display:flex;justify-content:flex-end;gap:7px}
    .npc-forge-class-guide__tabs button,.npc-forge-class-guide__subhead-actions button,.npc-forge-class-guide__subclass-confirm button{padding:7px 10px;border:1px solid rgba(255,255,255,.18);border-radius:7px;color:rgba(255,255,255,.88);background:rgba(255,255,255,.04);font-size:.7rem;font-weight:800}
    .npc-forge-class-guide__tabs button.is-active,.npc-forge-class-guide__subclass-confirm button.is-primary{border-color:rgba(var(--class-accent),.92);color:#fff;background:linear-gradient(180deg,rgba(var(--class-accent),.74),rgba(73,42,118,.82));box-shadow:0 0 18px rgba(var(--class-accent),.12)}
    .npc-forge-class-guide__overview-book{position:relative;padding:0!important;overflow:hidden;border:1px solid rgba(var(--class-accent),.28)!important;border-radius:14px!important;background:linear-gradient(150deg,rgba(18,20,34,.97),rgba(7,12,22,.985))!important;box-shadow:inset 0 1px rgba(255,255,255,.025),0 18px 46px rgba(0,0,0,.24)!important}
    .npc-forge-class-guide__overview-book::before{content:"";position:absolute;inset:8px;z-index:0;pointer-events:none;border:1px solid rgba(var(--class-accent),.07);border-radius:10px}
    .npc-forge-class-guide__overview-book>*{position:relative;z-index:1}
    .npc-forge-class-guide__book-hero{position:relative;display:grid!important;grid-template-columns:minmax(0,56%) minmax(300px,44%)!important;min-height:286px!important;overflow:hidden;border-bottom:1px solid rgba(var(--class-accent),.22)!important;background:linear-gradient(105deg,rgba(9,12,22,.98),rgba(19,17,32,.92) 53%,rgba(11,14,23,.42))!important}
    .npc-forge-class-guide__book-hero::before{content:"";position:absolute;inset:0;z-index:1;pointer-events:none;background:radial-gradient(circle at 74% 50%,rgba(var(--class-secondary),.12),transparent 22%),linear-gradient(90deg,rgba(5,8,15,.3),transparent 54%,rgba(5,8,15,.12))}
    .npc-forge-class-guide__book-hero::after{content:"";position:absolute;left:0;right:0;bottom:0;z-index:3;height:1px;background:linear-gradient(90deg,transparent,rgba(var(--class-accent),.66),rgba(var(--class-secondary),.4),transparent)}
    .npc-forge-class-guide__hero-copy{position:relative;z-index:4;display:grid;align-content:center;gap:10px;padding:28px clamp(20px,3vw,38px)}
    .npc-forge-class-guide__hero-kicker{display:flex;align-items:center;gap:8px;font-size:.58rem;font-weight:900;letter-spacing:.11em;text-transform:uppercase}
    .npc-forge-class-guide__hero-kicker span{color:rgb(var(--class-secondary))}.npc-forge-class-guide__hero-kicker em{padding:3px 6px;border:1px solid rgba(var(--class-accent),.2);border-radius:999px;color:rgba(255,255,255,.58);font-style:normal;letter-spacing:.04em}
    .npc-forge-class-guide__book-hero h2{margin:0!important;color:#fff!important;font-family:Georgia,"Times New Roman",serif;font-size:clamp(2rem,3.3vw,3.25rem)!important;font-weight:600!important;letter-spacing:.025em;line-height:1!important;text-shadow:0 4px 20px rgba(0,0,0,.44)}
    .npc-forge-class-guide__book-hero p{max-width:68ch;margin:0!important;color:rgba(255,255,255,.82)!important;font-size:.82rem!important;line-height:1.62!important}
    .npc-forge-class-guide__hero-art{position:relative;z-index:0;min-width:0;overflow:hidden}
    .npc-forge-class-guide__hero-art::before{content:"";position:absolute;inset:0;z-index:2;pointer-events:none;background:linear-gradient(90deg,rgba(10,12,21,.98) 0%,rgba(10,12,21,.62) 14%,transparent 46%),linear-gradient(0deg,rgba(7,10,18,.38),transparent 42%)}
    .npc-forge-class-guide__hero-art img{display:block;width:100%;height:100%;min-height:286px!important;object-fit:cover!important;object-position:center 34%!important;filter:saturate(.92) contrast(1.04) brightness(.88);transform:scale(1.04)}
    .npc-forge-class-guide.is-class-artificer .npc-forge-class-guide__hero-art img{object-position:center 30%!important;filter:saturate(1.02) contrast(1.06) brightness(.91)}
    .npc-forge-class-guide__hero-facts{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:7px!important;margin-top:4px!important}
    .npc-forge-class-guide__hero-facts>div{position:relative;display:grid!important;gap:3px!important;min-height:54px;padding:9px 10px 9px 32px!important;border:1px solid rgba(var(--class-accent),.18)!important;border-radius:8px!important;background:linear-gradient(145deg,rgba(32,25,48,.66),rgba(8,14,25,.72))!important;box-shadow:inset 0 1px rgba(255,255,255,.025)!important}
    .npc-forge-class-guide__hero-facts>div::before{content:"✦";position:absolute;left:10px;top:50%;transform:translateY(-50%);display:grid;place-items:center;width:16px;height:16px;border:1px solid rgba(var(--class-accent),.45);border-radius:50%;color:rgb(var(--class-secondary));background:rgba(var(--class-secondary),.06);font-size:.55rem}
    .npc-forge-class-guide__hero-facts span{color:rgba(255,255,255,.49)!important;font-size:.49rem!important;font-weight:800!important;letter-spacing:.06em!important;text-transform:uppercase}.npc-forge-class-guide__hero-facts strong{color:#fff!important;font-size:.64rem!important;line-height:1.3!important}
    .npc-forge-class-guide__overview-body{display:grid;gap:14px;padding:16px}
    .npc-forge-class-guide__detailed-controls{display:grid;gap:12px;padding:16px clamp(1rem,2.5vw,2rem) 0}
    .npc-forge-class-guide__subclasses{display:grid;gap:10px;padding:14px;border:1px solid rgba(var(--class-accent),.22);border-radius:11px;background:linear-gradient(145deg,rgba(27,23,43,.72),rgba(9,15,26,.82));box-shadow:inset 0 1px rgba(255,255,255,.02)}
    .npc-forge-class-guide__subclasses.is-required{border-color:rgba(255,121,121,.55);background:linear-gradient(145deg,rgba(76,24,39,.25),rgba(12,15,25,.84))}
    .npc-forge-class-guide__subhead{display:flex;align-items:center;justify-content:space-between;gap:12px}.npc-forge-class-guide__subhead>div:first-child{display:grid;gap:2px}.npc-forge-class-guide__subhead span{color:rgb(var(--class-secondary));font-size:.6rem;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.npc-forge-class-guide__subhead strong{color:#fff;font-size:.78rem}.npc-forge-class-guide__subhead-actions{display:flex;align-items:center;gap:8px}.npc-forge-class-guide__subhead-actions label,.npc-forge-class-guide__subclasses>p{color:rgba(255,255,255,.66);font-size:.66rem}
    .npc-forge-class-guide__subclass-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(112px,1fr));gap:7px}
    .npc-forge-class-guide__subclass-grid>button{display:flex;align-items:center;gap:7px;min-width:0;min-height:39px;padding:7px 8px;border:1px solid rgba(255,255,255,.12);border-radius:8px;color:rgba(255,255,255,.8);background:linear-gradient(145deg,rgba(15,18,29,.92),rgba(8,13,22,.96));text-align:left;transition:border-color .15s ease,background .15s ease,box-shadow .15s ease,transform .15s ease}
    .npc-forge-class-guide__subclass-grid>button:hover,.npc-forge-class-guide__subclass-grid>button:focus-visible{border-color:rgba(var(--class-secondary),.58);background:linear-gradient(145deg,rgba(18,42,50,.48),rgba(14,19,31,.96));outline:none;transform:translateY(-1px)}
    .npc-forge-class-guide__subclass-grid>button.is-active{border-color:rgba(var(--class-accent),.9);background:linear-gradient(145deg,rgba(var(--class-accent),.22),rgba(11,18,29,.96));box-shadow:inset 2px 0 rgba(var(--class-accent),.92),0 0 18px rgba(var(--class-accent),.08)}
    .npc-forge-class-guide__subclass-grid>button.is-selected{box-shadow:inset 2px 0 rgb(var(--class-secondary)),0 0 18px rgba(var(--class-secondary),.08)}
    .npc-forge-class-guide__subclass-mark{flex:0 0 auto;display:grid;place-items:center;width:22px;height:22px;border:1px solid rgba(var(--class-accent),.35);border-radius:50%;color:rgb(var(--class-secondary));background:rgba(var(--class-accent),.08);font-size:.65rem}
    .npc-forge-class-guide__subclass-label{display:grid;min-width:0;gap:1px}.npc-forge-class-guide__subclass-label strong{overflow:hidden;color:#fff;font-size:.64rem;line-height:1.2;text-overflow:ellipsis;white-space:nowrap}.npc-forge-class-guide__subclass-label small{overflow:hidden;color:rgba(255,255,255,.46);font-size:.49rem;line-height:1.2;text-overflow:ellipsis;white-space:nowrap}
    .npc-forge-class-guide__subclass-confirm{display:flex;align-items:center;justify-content:space-between;gap:10px;padding-top:2px}.npc-forge-class-guide__subclass-confirm>span{color:rgba(255,255,255,.58);font-size:.62rem}
    .npc-forge-class-guide__subclass-confirm button:disabled{opacity:.5;cursor:not-allowed}
    .npc-forge-class-guide__compare-drawer{border-top:1px solid rgba(255,255,255,.09);padding-top:8px}.npc-forge-class-guide__compare-drawer summary{color:#d8c4f8;cursor:pointer;font-size:.7rem;font-weight:800}.npc-forge-class-guide__compare-drawer>div{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:8px}.npc-forge-class-guide__compare-drawer button{display:grid;gap:4px;padding:9px;border:1px solid rgba(255,255,255,.1);border-radius:8px;color:#fff;background:rgba(255,255,255,.025);text-align:left}.npc-forge-class-guide__compare-drawer button.is-active{border-color:rgb(var(--class-accent));background:rgba(var(--class-accent),.15)}.npc-forge-class-guide__compare-drawer small,.npc-forge-class-guide__compare-drawer span{color:rgba(255,255,255,.63);font-size:.64rem;line-height:1.45}
    .npc-forge-class-guide__choice-routing{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:12px;padding:11px 13px;border:1px solid rgba(var(--class-secondary),.2);border-radius:10px;background:linear-gradient(90deg,rgba(var(--class-secondary),.06),rgba(7,13,22,.56));box-shadow:inset 0 1px rgba(255,255,255,.02)}
    .npc-forge-class-guide__choice-routing-icon{display:grid;place-items:center;width:34px;height:34px;border:1px solid rgba(var(--class-accent),.32);border-radius:50%;color:#e3c9ff;background:radial-gradient(circle,rgba(var(--class-accent),.16),rgba(7,11,20,.7));font-size:1rem}.npc-forge-class-guide__choice-routing>div:nth-child(2){display:grid;gap:3px}.npc-forge-class-guide__choice-routing>div:nth-child(2)>span{color:rgb(var(--class-secondary));font-size:.55rem;font-weight:900;letter-spacing:.09em;text-transform:uppercase}.npc-forge-class-guide__choice-routing>div:nth-child(2)>strong{color:#fff;font-size:.7rem}.npc-forge-class-guide__choice-routing>div:nth-child(2)>small{color:rgba(255,255,255,.58);font-size:.58rem;line-height:1.45}
    .npc-forge-class-guide__choice-routing-counts{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:6px}.npc-forge-class-guide__choice-routing-counts span{padding:5px 8px;border:1px solid rgba(var(--class-secondary),.12);border-radius:999px;color:#d8fff9;background:rgba(var(--class-secondary),.07);font-size:.57rem}.npc-forge-class-guide__choice-routing-counts b{color:#fff}
    .npc-forge-class-guide__section-title{display:flex;align-items:end;justify-content:space-between;gap:12px;padding:3px 3px 9px;border-bottom:1px solid rgba(var(--class-accent),.16)}.npc-forge-class-guide__section-title>span{color:#d7b6ff;font-family:Georgia,"Times New Roman",serif;font-size:.9rem;letter-spacing:.04em;text-transform:uppercase}.npc-forge-class-guide__section-title>small{color:rgba(255,255,255,.46);font-size:.55rem}
    .npc-forge-class-guide__table-card{display:grid;gap:8px;max-height:520px;overflow:auto!important;border:1px solid rgba(var(--class-accent),.2)!important;border-radius:10px!important;background:rgba(8,12,21,.78)!important}.npc-forge-class-guide__table-card .class-level-guide__row.is-head{position:sticky;top:0;z-index:2;background:linear-gradient(180deg,rgba(35,23,48,.98),rgba(18,18,31,.98))!important}.npc-forge-class-guide__table-card .class-level-guide__row.is-current{box-shadow:inset 3px 0 rgb(var(--class-secondary))}.npc-forge-class-guide__table-card .class-level-guide__features button{border:0;color:#d9c4ff;background:transparent;text-align:left;text-decoration:none}.npc-forge-class-guide__table-card .class-level-guide__features button:hover,.npc-forge-class-guide__table-card .class-level-guide__features button:focus-visible{color:#9cece2;text-decoration:underline;text-underline-offset:2px;outline:none}
    .npc-forge-class-guide__detail{min-height:130px}.npc-forge-class-guide__detail p,.npc-forge-class-guide__subclass-intro p,.npc-forge-class-guide .class-book-guide__feature p{color:rgba(255,255,255,.82)!important;font-size:.86rem!important;line-height:1.72!important}
    .npc-forge-class-guide__level-heading{margin-bottom:14px;padding:11px 13px;border:1px solid rgba(var(--class-accent),.35);border-radius:10px;background:linear-gradient(90deg,rgba(var(--class-accent),.14),rgba(var(--class-secondary),.035))}.npc-forge-class-guide__level-heading h3{margin-bottom:0}.npc-forge-class-guide .class-book-guide__levels>section{padding-top:1.35rem!important}.npc-forge-class-guide .class-book-guide__feature h4{font-size:1rem}.npc-forge-class-guide .class-book-guide__outline{top:0}.npc-forge-class-guide__warning,.npc-forge-class-guide__loading{padding:10px;border-radius:8px;color:#ffd5a2;background:rgba(132,73,24,.16)}
    body .npc-forge-class-feature-dock{border:1px solid rgba(182,116,255,.88)!important;border-radius:16px!important;background:radial-gradient(circle at 84% 14%,rgba(74,211,226,.09),transparent 26%),radial-gradient(circle at 18% 82%,rgba(170,92,255,.11),transparent 34%),linear-gradient(155deg,rgba(24,17,38,.992),rgba(8,13,24,.995) 58%,rgba(8,18,27,.992))!important;box-shadow:inset 0 0 0 1px rgba(255,255,255,.025),inset 0 0 34px rgba(119,68,183,.08),0 24px 72px rgba(0,0,0,.62),0 0 0 3px rgba(69,41,99,.24),0 0 42px rgba(126,72,199,.15)!important}
    body .npc-forge-class-feature-dock::before{content:"";position:absolute;inset:6px;z-index:0;pointer-events:none;border:1px solid rgba(177,123,255,.12);border-radius:11px;background:linear-gradient(135deg,rgba(255,255,255,.012),transparent 28%,transparent 72%,rgba(74,211,226,.018))}
    body .npc-forge-class-feature-dock::after{content:"✦";position:absolute;left:50%;top:-12px;z-index:5;transform:translateX(-50%);display:grid;place-items:center;width:28px;height:24px;border:1px solid rgba(182,116,255,.72);border-radius:50%;color:#a7f3f3;background:radial-gradient(circle,rgba(170,92,255,.56),rgba(20,14,34,.98) 68%);box-shadow:0 0 18px rgba(170,92,255,.4);font-size:.65rem}
    body .npc-forge-class-feature-dock__head,body .npc-forge-class-feature-dock__body{position:relative;z-index:2}
    body .npc-forge-class-feature-dock__head{padding:15px 16px 12px!important;border-bottom:1px solid rgba(182,116,255,.22)!important;background:linear-gradient(180deg,rgba(47,28,67,.96),rgba(16,18,31,.96))!important}
    body .npc-forge-class-feature-dock__title-group>span{color:#bbf7f3!important;font-size:.55rem!important;letter-spacing:.14em!important}
    body .npc-forge-class-feature-dock__title-group>h3{color:#f4eaff!important;font-family:Georgia,"Times New Roman",serif;font-size:1.12rem!important;font-weight:600!important;letter-spacing:.025em!important;text-shadow:0 3px 14px rgba(0,0,0,.35)}
    body .npc-forge-class-feature-dock__head-actions>em{border-color:rgba(74,211,226,.22)!important;color:#b8f4ef!important;background:rgba(74,211,226,.055)!important}
    body .npc-forge-class-feature-dock__head-actions>button{border-color:rgba(182,116,255,.5)!important;border-radius:8px!important;background:rgba(11,12,22,.82)!important}
    body .npc-forge-class-feature-dock__body{gap:14px!important;padding:16px 17px 18px!important;background-image:radial-gradient(circle at 84% 62%,rgba(170,92,255,.04),transparent 28%),linear-gradient(rgba(255,255,255,.012) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.009) 1px,transparent 1px);background-size:auto,34px 34px,34px 34px}
    body .npc-forge-class-feature-dock__class-chip{border-color:rgba(74,211,226,.28)!important;color:#c9fbf7!important;background:rgba(74,211,226,.055)!important}
    body .npc-forge-class-feature-dock__summary{padding:2px 1px;color:rgba(255,255,255,.88)!important}
    body .npc-forge-class-feature-dock__summary .class-feature-text,body .npc-forge-class-feature-dock__summary p{font-size:.75rem!important;line-height:1.65!important}
    body .npc-forge-class-feature-dock__summary li{font-size:.72rem!important;line-height:1.62!important}
    body .npc-forge-class-feature-dock__highlights{padding:11px 12px!important;border:1px solid rgba(182,116,255,.2)!important;border-left:3px solid rgba(74,211,226,.72)!important;border-radius:10px!important;background:linear-gradient(90deg,rgba(74,211,226,.055),rgba(170,92,255,.045))!important}
    body .npc-forge-class-feature-dock__highlights>strong{color:#cdb2ff!important;font-size:.54rem!important;letter-spacing:.1em!important}
    body .npc-forge-class-feature-dock__meta>span{border-color:rgba(182,116,255,.14)!important;background:rgba(9,12,21,.56)!important}
    body .npc-forge-class-feature-dock__routing-note{border-color:rgba(74,211,226,.18)!important;border-left-color:#4ad3e2!important;background:linear-gradient(90deg,rgba(18,74,82,.18),rgba(8,14,25,.42))!important}
    body .npc-forge-class-feature-dock__listed-note{border-color:rgba(182,116,255,.2)!important;border-left-color:#b674ff!important;background:linear-gradient(90deg,rgba(105,55,160,.14),rgba(8,14,25,.42))!important}
    body .npc-forge-class-feature-dock__drag-cue{color:rgba(255,255,255,.42)!important}.npc-forge-class-feature-dock__drag-cue span{color:#78e7df!important}
    @media(max-width:1120px){.npc-forge-class-guide__hero-facts{grid-template-columns:repeat(3,minmax(0,1fr))!important}.npc-forge-class-guide__book-hero{grid-template-columns:minmax(0,60%) minmax(260px,40%)!important}.npc-forge-class-guide__subclass-grid{grid-template-columns:repeat(auto-fit,minmax(104px,1fr))}}
    @media(max-width:900px){.npc-forge-class-guide__book-hero{grid-template-columns:1fr!important}.npc-forge-class-guide__hero-art{min-height:230px;order:-1}.npc-forge-class-guide__hero-art img{min-height:230px!important}.npc-forge-class-guide__hero-art::before{background:linear-gradient(0deg,rgba(10,12,21,.98),transparent 54%)}.npc-forge-class-guide__hero-copy{padding:20px}.npc-forge-class-guide__hero-facts{grid-template-columns:repeat(2,minmax(0,1fr))!important}.npc-forge-class-guide__choice-routing{grid-template-columns:auto 1fr}.npc-forge-class-guide__choice-routing-counts{grid-column:2;justify-content:flex-start}.npc-forge-class-guide__compare-drawer>div{grid-template-columns:1fr}}
    @media(max-width:760px){.npc-forge-class-guide__tabs{width:100%}.npc-forge-class-guide__tabs button{flex:1}.npc-forge-class-guide__subhead{align-items:stretch;flex-direction:column}.npc-forge-class-guide__subhead-actions{justify-content:space-between}.npc-forge-class-guide__subclass-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.npc-forge-class-guide__subclass-confirm{align-items:stretch;flex-direction:column}.npc-forge-class-guide__choice-routing{grid-template-columns:1fr}.npc-forge-class-guide__choice-routing-icon{display:none}.npc-forge-class-guide__choice-routing-counts{grid-column:auto}.npc-forge-class-guide__section-title{align-items:flex-start;flex-direction:column}.npc-forge-class-guide__hero-facts{grid-template-columns:1fr!important}}
  `}</style>;
}
