// Generated by scripts/generate_background_lore_catalog.mjs from reviewed 5etools data.
// Player-facing text is campaign-neutralized; mechanics remain source-authentic.
export const BACKGROUND_LORE_CATALOG = Object.freeze({
  "aberrant-heir|EFA": {
    "name": "Aberrant Heir",
    "source": "EFA",
    "lore": "Your aberrant dragonmark has made life challenging since it manifested. You might have hidden it successfully for most of your life or managed to avoid notice. Alternatively, you might have encountered suspicion and fear, perhaps coupled with the outright antagonism of one or more dragonmarked houses. You might have formed an association with the House Tarkanan criminal organization (named for one of the most notorious leaders of the aberrant dragonmarked in the War of the Mark twenty-five centuries ago). Or you might struggle to find your own way in the world, relying on your wits and the power of your mark.",
    "loreSource": "EFA:backgroundFluff"
  },
  "acolyte|XPHB": {
    "name": "Acolyte",
    "source": "XPHB",
    "lore": "You devoted yourself to service in a temple, either nestled in a town or secluded in a sacred grove. There you performed rites in honor of a god or pantheon. You served under a priest and studied religion. Thanks to your priest's instruction and your own devotion, you also learned how to channel a modicum of divine power in service to your place of worship and the people who prayed there.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "anthropologist|TOA": {
    "name": "Anthropologist",
    "source": "ToA",
    "lore": "You have always been fascinated by other cultures, from the most ancient and primeval lost lands to the most modern civilizations. By studying other cultures' customs, philosophies, laws, rituals, religious beliefs, languages, and art, you have learned how tribes, empires, and all forms of society in between craft their own destinies and doom. This knowledge came to you not only through books and scrolls, but also through firsthand observation—by visiting far-flung settlements and exploring local histories and customs.",
    "loreSource": "ToA:backgroundFluff"
  },
  "archaeologist|EFA": {
    "name": "Archaeologist",
    "source": "EFA",
    "lore": "You've made a lifelong study of the lost and fallen cultures of the past, visiting their ruins, deciphering their written records, and examining their surviving masterworks. Perhaps you studied at Morgrave University or a similar institution, supplementing your time in the library with fieldwork amid ancient ruins in remote locations. Some archaeologists plunder the treasures of the past in search of wealth or fame, but most consider it their calling to learn from the past. In any case, the archaeologists of the wider world combine the qualities of learned historians with the grit of treasure hunters.",
    "loreSource": "EFA:backgroundFluff"
  },
  "artisan|XPHB": {
    "name": "Artisan",
    "source": "XPHB",
    "lore": "You began mopping floors and scrubbing counters in an artisan's workshop for a few coppers per day as soon as you were strong enough to carry a bucket. When you were old enough to apprentice, you learned to create basic crafts of your own, as well as how to sweet-talk the occasional demanding customer. Your trade has also given you a keen eye for detail.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "astral-drifter|AAG": {
    "name": "Astral Drifter",
    "source": "AAG",
    "lore": "For longer than you can remember, you have traversed the Astral Sea. There, you experienced firsthand the wonders of the Silver Void: you stopped aging and no longer felt hunger or thirst. Driven by wanderlust, you drifted from one part of the Astral Sea to another, like a mote of dust on the wind. You have lost count of the decades that have passed since you arrived here. In your travels, you have camped on the petrified hulks of dead gods and narrowly escaped the psychic winds that sweep across the Astral Sea while also avoiding prolonged contact with the plane's most dangerous denizens.",
    "loreSource": "AAG:backgroundFluff"
  },
  "athlete|MOT": {
    "name": "Athlete",
    "source": "MOT",
    "lore": "You strive to perfect yourself physically and in execution of everything you do. The thrill of competition lights fire in your blood, and the roar of the crowd drives you forward. Tales of your exploits precede you and might open doors or loosen tongues. Whether in one of the poleis, between them, or among the nonhuman peoples of the wider world, physical contests and those who pursue them command respect bordering on reverence. Athletes arise from all walks of life and all cultures and quite often cross paths with one another.",
    "loreSource": "MOT:backgroundFluff"
  },
  "augen-trust-spy|EGW": {
    "name": "Augen Trust (Spy)",
    "source": "EGW",
    "lore": "Your years as Augen Trust (Spy) taught you to trade in trust, secrets, and carefully managed identities. Decide who recruited you, which loyalty matters most, and what information could still place you in danger.",
    "loreSource": "campaign-neutral-fallback"
  },
  "azorius-functionary|GGR": {
    "name": "Azorius Functionary",
    "source": "GGR",
    "lore": "The brutes are at the gate, chaos is looming, and the only thing standing in the way of disaster is the foundation of law and order—as embodied in the Azorius Senate. You're a proud member of the Azorius guild, which both enacts and enforces the laws that make metropolitan society function smoothly and safely.",
    "loreSource": "GGR:backgroundFluff"
  },
  "baldurs-gate-acolyte|BGDIA": {
    "name": "Baldur's Gate Acolyte",
    "source": "BGDIA",
    "lore": "Your time as Acolyte bound you to a faith, mystery, or sacred community. Decide what revelation or duty shaped you, who shares your beliefs, and what could cause your devotion to deepen—or fracture.",
    "loreSource": "campaign-neutral-fallback"
  },
  "baldurs-gate-charlatan|BGDIA": {
    "name": "Baldur's Gate Charlatan",
    "source": "BGDIA",
    "lore": "Everybody's always trying to get a leg up on somebody in a sprawling trade city. One group's con artist might be another's revolutionary. Or maybe you're just in it for yourself. In any case, characters with this background have a plan to hit the big time; all they need is audacity and a little time.",
    "loreSource": "BGDIA:backgroundFluff"
  },
  "baldurs-gate-criminal|BGDIA": {
    "name": "Baldur's Gate Criminal",
    "source": "BGDIA",
    "lore": "No career criminal in a sprawling trade city operates without being aware of the Guild. Some studiously keep a low profile, carrying just the occasional smuggled load in with legitimate merchandise, or only breaking knees when it can plausibly be claimed as an act of personal revenge. Others join up with crews for protection, or with the Guild itself. A few former Guild members have been cast out of the organization due to incompetence or after offending a more powerful member, and now shuffle for scraps to survive.",
    "loreSource": "BGDIA:backgroundFluff"
  },
  "baldurs-gate-entertainer|BGDIA": {
    "name": "Baldur's Gate Entertainer",
    "source": "BGDIA",
    "lore": "As Entertainer, you learned how reputation and public attention can change a person's fortunes. Your admirers, competitors, and most memorable performance still shape how others receive you.",
    "loreSource": "campaign-neutral-fallback"
  },
  "baldurs-gate-folk-hero|BGDIA": {
    "name": "Baldur's Gate Folk Hero",
    "source": "BGDIA",
    "lore": "a sprawling trade city is a city badly in need of heroes, and every so often, one rises from among its own. Ordinary people who rise to greatness are beloved in local history, but the popular imagination can turn on such champions almost as quickly as it anoints them.",
    "loreSource": "BGDIA:backgroundFluff"
  },
  "baldurs-gate-guild-artisan|BGDIA": {
    "name": "Baldur's Gate Guild Artisan",
    "source": "BGDIA",
    "lore": "Numerous guilds and professional associations exist in a sprawling trade city, covering every imaginable trade and discipline from gravediggers to moneylenders.",
    "loreSource": "BGDIA:backgroundFluff"
  },
  "baldurs-gate-hermit|BGDIA": {
    "name": "Baldur's Gate Hermit",
    "source": "BGDIA",
    "lore": "While some might think it strange to find hermits in a bustling city, others know that sometimes the most profound solitude exists in the midst of a crowd. a sprawling trade city holds a handful of souls who manage to find isolation amid its tumult.",
    "loreSource": "BGDIA:backgroundFluff"
  },
  "baldurs-gate-noble|BGDIA": {
    "name": "Baldur's Gate Noble",
    "source": "BGDIA",
    "lore": "You were raised around status, obligation, reputation, and the long memory of an influential family or court. Your name and manners can open doors, but they also bind you to inherited duties, ambitious relatives, old alliances, and enemies you did not choose.",
    "loreSource": "campaign-neutral-fallback"
  },
  "baldurs-gate-outlander|BGDIA": {
    "name": "Baldur's Gate Outlander",
    "source": "BGDIA",
    "lore": "As Outlander, you learned to live between places and cultures. The journey changed how you see ordinary life, while the homeland, route, or people left behind remain a powerful part of your story.",
    "loreSource": "campaign-neutral-fallback"
  },
  "baldurs-gate-sage|BGDIA": {
    "name": "Baldur's Gate Sage",
    "source": "BGDIA",
    "lore": "As Sage, you pursued knowledge through study, travel, or firsthand investigation. Your work connected you to mentors, institutions, and a discovery whose importance may only now be becoming clear.",
    "loreSource": "campaign-neutral-fallback"
  },
  "baldurs-gate-sailor|BGDIA": {
    "name": "Baldur's Gate Sailor",
    "source": "BGDIA",
    "lore": "Your life as Sailor shaped the habits, relationships, and hard-earned experience you carried into adventuring. Decide who taught you, what ended that chapter of your life, and which person, place, or obligation still connects you to it.",
    "loreSource": "campaign-neutral-fallback"
  },
  "baldurs-gate-soldier|BGDIA": {
    "name": "Baldur's Gate Soldier",
    "source": "BGDIA",
    "lore": "Mercenaries, private guards, Watch soldiers, and members of the Flaming Fist number among just a few of the many soldiers on the streets of a sprawling trade city.",
    "loreSource": "BGDIA:backgroundFluff"
  },
  "baldurs-gate-urchin|BGDIA": {
    "name": "Baldur's Gate Urchin",
    "source": "BGDIA",
    "lore": "Surviving as Urchin required nerve, useful contacts, and a flexible relationship with authority. Someone from that life may still consider you a partner, a debtor, a rival, or a loose end.",
    "loreSource": "campaign-neutral-fallback"
  },
  "boros-legionnaire|GGR": {
    "name": "Boros Legionnaire",
    "source": "GGR",
    "lore": "As a member of the Boros Legion, your life is devoted to the service of angels and consecrated to the work of establishing justice and peace on the streets of a vast metropolis. You might be a true believer, inspired by the example of the angels, moved by the plight of the downtrodden, and devoted to the cause of justice. Or you could be a cynic in the ranks, perhaps because you reluctantly followed in the footsteps of a Boros parent, succumbed to the persuasion of a charismatic recruiter's lofty promises, or were drawn in by the prospect of a life of action.",
    "loreSource": "GGR:backgroundFluff"
  },
  "carouser|ABH": {
    "name": "Carouser",
    "source": "ABH",
    "lore": "You grew to adulthood in the beating heart of a large city, such as a sprawling trade city. You spent countless evenings in taverns, playhouses, parlors, and gambling dens, savoring all the city had to offer. You're a natural at interacting with people to learn their secrets, whether over a high-stakes game or at a high-class soiree. You might have been thrown out of an establishment or ten, but only by people who don't know how to party.",
    "loreSource": "ABH:backgroundFluff"
  },
  "celebrity-adventurers-scion|AI": {
    "name": "Celebrity Adventurer's Scion",
    "source": "AI",
    "lore": "Your family name strikes fear and admiration in the hearts of the common folk—but that's got nothing to do with you. Songs and stories celebrating the adventuring exploits of your famous parent are widely known. Kids across the land grew up wishing they were you. But being the child of a famous adventurer wasn't all hugs and kisses. You seldom saw your celebrity-adventurer parent, and when they were around, it was all about them and tales of slaying this demon or vanquishing that dragon. All too often, you'd be woken out of a sound sleep by someone standing outside your home screaming about the latest threat to the town, the region, or the world.",
    "loreSource": "AI:backgroundFluff"
  },
  "charlatan|XPHB": {
    "name": "Charlatan",
    "source": "XPHB",
    "lore": "Once you were old enough to order an ale, you soon had a favorite stool in every tavern within ten miles of where you were born. As you traveled the circuit from public house to watering hole, you learned to prey on unfortunates who were in the market for a comforting lie or two—perhaps a sham potion or forged ancestry records.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "chondathan-freebooter|FRHOF": {
    "name": "Chondathan Freebooter",
    "source": "FRHoF",
    "lore": "Your life as Freebooter shaped the habits, relationships, and hard-earned experience you carried into adventuring. Decide who taught you, what ended that chapter of your life, and which person, place, or obligation still connects you to it.",
    "loreSource": "campaign-neutral-fallback"
  },
  "city-watch|SCAG": {
    "name": "City Watch",
    "source": "SCAG",
    "lore": "You have served the community where you grew up, standing as its first line of defense against crime. You aren't a soldier, directing your gaze outward at possible enemies. Instead, your service to your hometown was to help police its populace, protecting the citizenry from lawbreakers and malefactors of every stripe. You might have been part of the City Watch of a great cosmopolitan city, the baton-wielding police force of the City of Splendors, protecting the common folk from thieves and rowdy nobility alike. Or you might have been one of the valiant defenders of Silverymoon, a member of the Silverwatch or even one of the magic-wielding Spellguard.",
    "loreSource": "SCAG:backgroundFluff"
  },
  "clan-crafter|SCAG": {
    "name": "Clan Crafter",
    "source": "SCAG",
    "lore": "The Stout Folk are well known for their artisanship and the worth of their handiworks, and you have been trained in that ancient tradition. For years you labored under a dwarf master of the craft, enduring long hours and dismissive, sour-tempered treatment in order to gain the fine skills you possess today. You are most likely a dwarf, but not necessarily—particularly in the North, the shield dwarf clans learned long ago that only proud fools who are more concerned for their egos than their craft turn away promising apprentices, even those of other races. If you aren't a dwarf, however, you have taken a solemn oath never to take on an apprentice in the craft: it is not for non-dwarves to pass on the skills of Moradin's favored children. You would have no difficulty, however, finding a dwarf master who was willing to receive potential apprentices who came with your recommendation.",
    "loreSource": "SCAG:backgroundFluff"
  },
  "cloistered-scholar|SCAG": {
    "name": "Cloistered Scholar",
    "source": "SCAG",
    "lore": "As Cloistered Scholar, you pursued knowledge through study, travel, or firsthand investigation. Your work connected you to mentors, institutions, and a discovery whose importance may only now be becoming clear.",
    "loreSource": "campaign-neutral-fallback"
  },
  "cobalt-scholar-sage|EGW": {
    "name": "Cobalt Scholar (Sage)",
    "source": "EGW",
    "lore": "As Cobalt Scholar (Sage), you pursued knowledge through study, travel, or firsthand investigation. Your work connected you to mentors, institutions, and a discovery whose importance may only now be becoming clear.",
    "loreSource": "campaign-neutral-fallback"
  },
  "courtier|SCAG": {
    "name": "Courtier",
    "source": "SCAG",
    "lore": "You were raised around status, obligation, reputation, and the long memory of an influential family or court. Your name and manners can open doors, but they also bind you to inherited duties, ambitious relatives, old alliances, and enemies you did not choose.",
    "loreSource": "campaign-neutral-fallback"
  },
  "criminal|XPHB": {
    "name": "Criminal",
    "source": "XPHB",
    "lore": "You eked out a living in dark alleyways, cutting purses or burgling shops. Perhaps you were part of a small gang of like-minded wrongdoers who looked out for each other. Or maybe you were a lone wolf, fending for yourself against the local thieves' guild and more fearsome lawbreakers.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "custom-background|PHB": {
    "name": "Custom Background",
    "source": "PHB",
    "lore": "Your life as Custom Background shaped the habits, relationships, and hard-earned experience you carried into adventuring. Decide who taught you, what ended that chapter of your life, and which person, place, or obligation still connects you to it.",
    "loreSource": "campaign"
  },
  "dead-magic-dweller|FRHOF": {
    "name": "Dead Magic Dweller",
    "source": "FRHoF",
    "lore": "Your life as Dead Magic Dweller shaped the habits, relationships, and hard-earned experience you carried into adventuring. Decide who taught you, what ended that chapter of your life, and which person, place, or obligation still connects you to it.",
    "loreSource": "campaign-neutral-fallback"
  },
  "dimir-operative|GGR": {
    "name": "Dimir Operative",
    "source": "GGR",
    "lore": "You're a spy. Secrets and misinformation are your stock in trade. You skulk in the shadows, infiltrate other guilds, and steal the most precious secrets, whether they're written in locked journals or hidden away in someone's mind. Even you might not be aware of all the reasons behind the missions you carry out. Sometimes a mission's sole purpose is to conceal the motivation behind another strike performed in a different part of the city, or simply to spread fear. As part of your covert work for House Dimir, you maintain a false identity as a member of another guild. You can choose your secondary guild or roll to determine it randomly. This secondary guild membership determines a portion of your starting equipment and is also where most of your contacts come from. You infiltrate your secondary guild to learn its secrets, keep tabs on its activities, or perhaps undermine it from within.",
    "loreSource": "GGR:backgroundFluff"
  },
  "dragon-cultist|FRHOF": {
    "name": "Dragon Cultist",
    "source": "FRHoF",
    "lore": "You are an initiate of the Cult of the Dragon. You discovered or were brought to a cell cult, where you exemplified the values honored by dragon cultists: duplicity, secrecy, and determination. In exchange for your oath to serve the cult, the cult offered you the company of fellow dragon worshipers, plus access to resources that might help further your studies in the realms of arcana and occultism.",
    "loreSource": "FRHoF:backgroundFluff"
  },
  "emerald-enclave-caretaker|FRHOF": {
    "name": "Emerald Enclave Caretaker",
    "source": "FRHoF",
    "lore": "As a Caretaker with the Emerald Enclave, you take care of those who care for the world. Either alongside your fellow Emerald Enclave members or by yourself, you've learned essential skills for living with the land: how to track game, where to forage for useful herbs, and even how to forecast the weather. You use these talents to maintain the balance between civilization and the wilds and to rid the world of unnatural creatures.",
    "loreSource": "FRHoF:backgroundFluff"
  },
  "entertainer|XPHB": {
    "name": "Entertainer",
    "source": "XPHB",
    "lore": "You spent much of your youth following roving fairs and carnivals, performing odd jobs for musicians and acrobats in exchange for lessons. You may have learned how to walk a tightrope, how to play a lute in a distinct style, or how to recite poetry with impeccable diction. To this day, you thrive on applause and long for the stage.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "faceless|BGDIA": {
    "name": "Faceless",
    "source": "BGDIA",
    "lore": "Being who you are, you could never be a hero. Whether due to your class, your people, your family, or your sins, something about you prevents you from effectively pursuing the path you've chosen. Even so, that doesn't stop you. You've left your old face behind, taking on a new persona, becoming something more. Characters with the faceless background don a disguise—literally or otherwise—as they adventure. This persona might be dramatic or subtle. In a way, though, many characters have such larger than life personalities. Therefore, this background largely focuses on detailing the hero behind the mask.",
    "loreSource": "BGDIA:backgroundFluff"
  },
  "faction-agent|SCAG": {
    "name": "Faction Agent",
    "source": "SCAG",
    "lore": "Your years as Faction Agent taught you to trade in trust, secrets, and carefully managed identities. Decide who recruited you, which loyalty matters most, and what information could still place you in danger.",
    "loreSource": "campaign-neutral-fallback"
  },
  "failed-merchant|AI": {
    "name": "Failed Merchant",
    "source": "AI",
    "lore": "Maybe you come from a long line of merchants. Perhaps you were an entrepreneur. Regardless, your ventures ended poorly. Whether it was because of outside influences, bad luck, or simply because your business acumen was weak, you lost everything. With failure, however, comes experience. You're free of that old life, having made some connections and learned your lessons. Prepared to pursue the life of an adventurer, your insight into the world of commerce brought you into the sphere of Acquisitions Incorporated—and a franchise just might be in your future.",
    "loreSource": "AI:backgroundFluff"
  },
  "far-traveler|SCAG": {
    "name": "Far Traveler",
    "source": "SCAG",
    "lore": "As Far Traveler, you learned to live between places and cultures. The journey changed how you see ordinary life, while the homeland, route, or people left behind remain a powerful part of your story.",
    "loreSource": "campaign-neutral-fallback"
  },
  "farmer|XPHB": {
    "name": "Farmer",
    "source": "XPHB",
    "lore": "You grew up close to the land. Years tending animals and cultivating the earth rewarded you with patience and good health. You have a keen appreciation for nature's bounty alongside a healthy respect for nature's wrath.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "feylost|WBTW": {
    "name": "Feylost",
    "source": "WBtW",
    "lore": "You grew up in the Feywild after disappearing from your home plane as a child. Perhaps you were spirited away by kindly Fey who thought you were destined for great things. Perhaps you stumbled through a fey crossing by chance during a twilight stroll in the woods. Perhaps you were kidnapped by evil Fey but escaped from their clutches. Whatever the manner of your disappearance, you gradually fell under the Feywild's spell and learned a little about the nature of the mercurial tricksters that dwell there. When you finally returned to your home plane, you did not come back unchanged. You are haunted by the fact that the Feywild—a mirror world hidden behind a mere twist of perception—is only a hair's breadth away. Although your memories of the Feywild grow fainter with each passing day, your heart swells with a mixture of fear and joy at the prospect of one day venturing back to the Plane of Faerie—your home away from home.",
    "loreSource": "WBtW:backgroundFluff"
  },
  "fisher|GOS": {
    "name": "Fisher",
    "source": "GoS",
    "lore": "You have spent your life aboard fishing vessels or combing the shallows for the bounty of the ocean. Perhaps you were born into a family of fisher folk, working with your kin to feed your village. Maybe the job was a means to an end—a way out of an undesirable circumstance that forced you to take up life aboard a ship. Regardless of how you began, you soon fell in love with the sea, the art of fishing, and the promise of the eternal horizon.",
    "loreSource": "GoS:backgroundFluff"
  },
  "flaming-fist-mercenary|FRHOF": {
    "name": "Flaming Fist Mercenary",
    "source": "FRHoF",
    "lore": "Life as Flaming Fist Mercenary placed you inside a disciplined martial tradition with its own duties, comrades, and scars. Decide which campaign defined you and whether your former allegiance is a source of pride, regret, or unfinished business.",
    "loreSource": "campaign-neutral-fallback"
  },
  "folk-hero|PHB": {
    "name": "Folk Hero",
    "source": "PHB",
    "lore": "You come from a humble social rank, but you are destined for so much more. Already the people of your home village regard you as their champion, and your destiny calls you to stand against the tyrants and monsters that threaten the common folk everywhere.",
    "loreSource": "PHB:backgroundFluff"
  },
  "gambler|AI": {
    "name": "Gambler",
    "source": "AI",
    "lore": "All you need to make a lot of gold is a little gold. Except at those times when all you need to have no gold at all is a little gold. Whether you're a good gambler or a bad one rarely matters, because no one can divine the whims of Lady Luck. Sometimes you're up, sometimes you're down. But the thing about gambling is that someone is always willing to take a bet.",
    "loreSource": "AI:backgroundFluff"
  },
  "gate-warden|SATO": {
    "name": "Gate Warden",
    "source": "SatO",
    "lore": "You spent a significant amount of time somewhere influenced by intense planar forces or a portal to another plane of existence, such as one of the gatetowns in the Outlands. You're accustomed to experiences that would leave others reeling in terror or enraptured by otherworldly beauty, and you're as comfortable dealing with Celestials and Fiends as you are with the vendors in town (who might be one and the same).",
    "loreSource": "SatO:backgroundFluff"
  },
  "genie-touched|FRHOF": {
    "name": "Genie Touched",
    "source": "FRHoF",
    "lore": "Although genies no longer rule Calimshan, genie magic is still common in your homeland. Perhaps you inadvertently summoned a djinni from a magic lamp, or maybe you came upon an oasis guarded by a marid. A dao might have saved you from a landslide, or you bargained with an efreeti for fleeting wealth. However your fate intersected with that of a genie, the experience left you with a keen eye, a silver tongue, and more than a touch of magic.",
    "loreSource": "FRHoF:backgroundFluff"
  },
  "giant-foundling|BGG": {
    "name": "Giant Foundling",
    "source": "BGG",
    "lore": "Though you aren't a Giant, you grew up among giants. Maybe you were an orphan taken in by a sympathetic family of stone giants who raised you as one of their own. Or perhaps you lived in a lost prehistoric pocket of the world, surrounded by giants and fearsome behemoths or hulking dinosaurs. Something about your environment—perhaps the food or water that sustained you, elemental magic inherent in the site of your home, or some verdant blessing of growth placed on you—caused you to grow to a remarkable size for your kind. With the aid of this magic, you have learned how to embody the might of giants. You are used to moving through a world much bigger than you, and that is reflected in your skills, attitude, and perspective on life.",
    "loreSource": "BGG:backgroundFluff"
  },
  "golgari-agent|GGR": {
    "name": "Golgari Agent",
    "source": "GGR",
    "lore": "You are a member of a teeming horde—one small part of a sprawling organism. Just as you are part of the swarm, the swarm is part of a larger ecosystem, a never-ending cycle of life, death, rot, and rebirth. You have spent your life in the slow churn of that ecosystem, in the dark places of the city where the messy parts of existence are on display. There is little squeamishness among the Golgari, no fear of death or taboo about the dead, just a fierce affirmation of the cycle.",
    "loreSource": "GGR:backgroundFluff"
  },
  "grinner|EGW": {
    "name": "Grinner",
    "source": "EGW",
    "lore": "Your life as Grinner shaped the habits, relationships, and hard-earned experience you carried into adventuring. Decide who taught you, what ended that chapter of your life, and which person, place, or obligation still connects you to it.",
    "loreSource": "campaign-neutral-fallback"
  },
  "gruul-anarch|GGR": {
    "name": "Gruul Anarch",
    "source": "GGR",
    "lore": "The entire world of a vast metropolis is a sprawling metropolis, but you are a native of the wild areas that still exist—the abandoned districts, the rubblebelts, the overgrown parks, and the crumbling ruins. You are part of a savage society that clings desperately to the Old Ways—attuned to nature, full of primal rage, and given short shrift by a world consumed with continuing civilization's march of progress.",
    "loreSource": "GGR:backgroundFluff"
  },
  "guard|XPHB": {
    "name": "Guard",
    "source": "XPHB",
    "lore": "Your feet ache when you remember the countless hours you spent at your post in the tower. You were trained to keep one eye looking outside the wall, watching for marauders sweeping from the nearby forest, and your other eye looking inside the wall, searching for cutpurses and troublemakers.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "guide|XPHB": {
    "name": "Guide",
    "source": "XPHB",
    "lore": "You came of age outdoors, far from settled lands. Your home was anywhere you chose to spread your bedroll. There are wonders in the wilderness—strange monsters, pristine forests and streams, overgrown ruins of great halls once trod by giants—and you learned to fend for yourself as you explored them. From time to time, you guided friendly nature priests who instructed you in the fundamentals of channeling the magic of the wild.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "guild-artisan|PHB": {
    "name": "Guild Artisan",
    "source": "PHB",
    "lore": "You are a member of an artisan's guild, skilled in a particular field and closely associated with other artisans. You are a well-established part of the mercantile world, freed by talent and wealth from the constraints of a feudal social order. You learned your skills as an apprentice to a master artisan, under the sponsorship of your guild, until you became a master in your own right.",
    "loreSource": "PHB:backgroundFluff"
  },
  "harper|FRHOF": {
    "name": "Harper",
    "source": "FRHoF",
    "lore": "You accepted an invitation to join the Harpers, pledging an oath to uphold the Harper code and act in service to the common good. Like all Harpers, you understand the value of teamwork as well as when it's best to go it alone. Harper veterans have taught you the order's secrets—magical melodies, special watchwords, and legerdemain—and have entrusted you to use such knowledge to surveil and undermine the forces of evil.",
    "loreSource": "FRHoF:backgroundFluff"
  },
  "haunted-one|RHW": {
    "name": "Haunted One",
    "source": "RHW",
    "lore": "You are haunted by the events of your past. Whether it was a lone terrible incident or an accumulation of painful moments, you bear the unshakable weight of what happened to you. You've tried to bury it and run away from it, to no avail; it can't be slain with a sword or banished via magic. Nevertheless, you persist.",
    "loreSource": "RHW:backgroundFluff"
  },
  "hermit|XPHB": {
    "name": "Hermit",
    "source": "XPHB",
    "lore": "You spent your early years secluded in a hut or monastery located well beyond the outskirts of the nearest settlement. In those days, your only companions were the creatures of the forest and those who would occasionally visit to bring news of the outside world and supplies. The solitude allowed you to spend many hours pondering the mysteries of creation.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "house-agent|EFA": {
    "name": "House Agent",
    "source": "EFA",
    "lore": "You are connected to one of the dragonmarked houses, but you haven't (yet) manifested a dragonmark. You might be a member of the family by birth or an employee of the house with no familial connection. You've earned your living by doing the business of the house, serving as the hands, feet, and eyes of house leadership in the world. You might have many old friends, mentors, and rivals in the house you serve, plus allies or enemies in other houses.",
    "loreSource": "EFA:backgroundFluff"
  },
  "house-cannith-heir|EFA": {
    "name": "House Cannith Heir",
    "source": "EFA",
    "lore": "As a scion of House Cannith, you carry a proud legacy. Cannith creates wonders of the modern world, and you're expected to contribute to the ongoing success of the house through invention, scholarship, business, or diplomacy. The only thing that can stand in your way is the deep rift within your own house. The sooner the three barons sort out which of them is the true head of the house (and you, no doubt, have your preference), the sooner House Cannith can claim its rightful position of leadership among all the dragonmarked houses.",
    "loreSource": "EFA:backgroundFluff"
  },
  "house-deneith-heir|EFA": {
    "name": "House Deneith Heir",
    "source": "EFA",
    "lore": "As an heir of House Deneith, you've been trained for combat—not to seek it out, but not to shy from it either. You've learned the importance of duty, honor, and the laws used to govern society when duty and honor fail. As you established your name in the house, you might have worked as a bodyguard for some minor dignitary, as a mercenary, or as a marshal hunting fugitives. Now you're prepared to claim your rightful standing in the mightiest of the dragonmarked houses.",
    "loreSource": "EFA:backgroundFluff"
  },
  "house-ghallanda-heir|EFA": {
    "name": "House Ghallanda Heir",
    "source": "EFA",
    "lore": "Thanks to your connections to House Ghallanda, you grew up accustomed to creature comforts, lively conversation, good drink, and delicious food. You might be a charming and witty scion of the house who loves nothing more than a pleasant evening beside a warm hearth. Or you could be a schemer who exploits bonds of trust and friendship to bend others to your will. You might pursue an adventuring career to master the cuisines of other cultures and ages, expand your network of useful contacts, or earn enough money to open your own inn.",
    "loreSource": "EFA:backgroundFluff"
  },
  "house-jorasco-heir|EFA": {
    "name": "House Jorasco Heir",
    "source": "EFA",
    "lore": "House Jorasco teaches that illness and injury stalk the living like ghosts, robbing people of health and longevity. You've been taught ways to combat these scourges, both magically and medically. You're trained to use those skills in the service of others—and to ascertain that you are always appropriately compensated for this service, ensuring the health and longevity of House Jorasco. You might be a kindly healer with no stomach for combat or a dispassionate specialist who knows exactly how to incapacitate or kill an enemy with precise strikes.",
    "loreSource": "EFA:backgroundFluff"
  },
  "house-kundarak-heir|EFA": {
    "name": "House Kundarak Heir",
    "source": "EFA",
    "lore": "You were raised around status, obligation, reputation, and the long memory of an influential family or court. Your name and manners can open doors, but they also bind you to inherited duties, ambitious relatives, old alliances, and enemies you did not choose.",
    "loreSource": "campaign-neutral-fallback"
  },
  "house-lyrandar-heir|EFA": {
    "name": "House Lyrandar Heir",
    "source": "EFA",
    "lore": "You were raised around status, obligation, reputation, and the long memory of an influential family or court. Your name and manners can open doors, but they also bind you to inherited duties, ambitious relatives, old alliances, and enemies you did not choose.",
    "loreSource": "campaign-neutral-fallback"
  },
  "house-medani-heir|EFA": {
    "name": "House Medani Heir",
    "source": "EFA",
    "lore": "As a member of House Medani, your life revolves around subterfuge—not engaging in it, but preventing others from doing so. You see the world around you as an intricate web of schemes, plots, and counterplots. Assessing the range of possibilities, you use instinct to predict threats to your clients and defend against them well before those threats can turn into danger. Defending against an assassin's blade is a job any Deneith sellsword or Tharashk enforcer can do—making sure no one ever draws that blade is the Medani way.",
    "loreSource": "EFA:backgroundFluff"
  },
  "house-orien-heir|EFA": {
    "name": "House Orien Heir",
    "source": "EFA",
    "lore": "You were raised around status, obligation, reputation, and the long memory of an influential family or court. Your name and manners can open doors, but they also bind you to inherited duties, ambitious relatives, old alliances, and enemies you did not choose.",
    "loreSource": "campaign-neutral-fallback"
  },
  "house-phiarlan-heir|EFA": {
    "name": "House Phiarlan Heir",
    "source": "EFA",
    "lore": "Though you have seen wealth, fame, and beauty as a child of House Phiarlan, you consider knowledge (and the power it brings) the greatest treasure of all. You might pursue that power as an artist or performer, always alert for secrets even as you regale the world with story, song, acrobatics, or art. Or you might foster ties to the secretive espionage arm of your house: the Serpentine Table.",
    "loreSource": "EFA:backgroundFluff"
  },
  "house-sivis-heir|EFA": {
    "name": "House Sivis Heir",
    "source": "EFA",
    "lore": "For nearly thirty centuries, your family has worked to maintain order. Communication is the cord that binds civilization together, and your ancestors settled the disputes of sovereigns and helped the dragonmarked houses find a place in the world. Few people realize the influence House Sivis has had on the shape of the modern age—just as few know how often a royal adviser holds more power than the actual ruler. While the other dragonmarked houses fight for fame and recognition, House Sivis plays a long game of subtle influence behind the scenes, keeping order amid the chaos of unending intrigue.",
    "loreSource": "EFA:backgroundFluff"
  },
  "house-tharashk-heir|EFA": {
    "name": "House Tharashk Heir",
    "source": "EFA",
    "lore": "Heirs of other houses lead lives of luxury, but in House Tharashk you learned self-reliance from an early age. What your young house lacks in resources, it makes up for in spirit and determination. Tharashk has a destiny to fulfill, and you have a part in it. Whether in combat or in social interaction, you have learned to play the role of the hunter: study your enemies, exploit their weaknesses, and do whatever it takes to achieve victory.",
    "loreSource": "EFA:backgroundFluff"
  },
  "house-thuranni-heir|EFA": {
    "name": "House Thuranni Heir",
    "source": "EFA",
    "lore": "Given House Thuranni's short history and focus on espionage, its leaders expect you to further the interests of the house at every opportunity. During the house's formative years as an independent entity, every move you make has been watched closely. This isn't to say that every Thuranni heir must actively spy at the behest of house elders. But even the house's most insular artists and artisans must keep up with current political events and pass on or collect information when asked.",
    "loreSource": "EFA:backgroundFluff"
  },
  "house-vadalis-heir|EFA": {
    "name": "House Vadalis Heir",
    "source": "EFA",
    "lore": "You have grown up with respect for both family and nature. You understand the culture of the Five Nations, but you don't get drawn into the games of ambition and status that others play. You know the beauty and power inherent in life, the mysteries of birth and death, and the miracles that happen in between. Your insights into the natural world allow you to see through the lies and deception of city folk—and never let on how much of their subterfuge you recognize.",
    "loreSource": "EFA:backgroundFluff"
  },
  "ice-fisher|FRHOF": {
    "name": "Ice Fisher",
    "source": "FRHoF",
    "lore": "You come from a proud line of fishers who work frozen lakes and dangerous winter waters. It is an honest but unforgiving trade: you learned to judge thin ice, wrestle heavy catches from freezing water, maintain simple gear, and endure long hours of cold without losing focus. Those experiences toughened both your body and your patience for a life of adventuring.",
    "loreSource": "campaign-neutral-override"
  },
  "inheritor|SCAG": {
    "name": "Inheritor",
    "source": "SCAG",
    "lore": "You are the heir to something of great value—not mere coin or wealth, but an object that has been entrusted to you and you alone. Your inheritance might have come directly to you from a member of your family, by right of birth, or it could have been left to you by a friend, a mentor, a teacher, or someone else important in your life. The revelation of your inheritance changed your life, and might have set you on the path to adventure, but it could also come with many dangers, including those who covet your gift and want to take it from you—by force, if need be.",
    "loreSource": "SCAG:backgroundFluff"
  },
  "initiate|PSA": {
    "name": "Initiate",
    "source": "PSA",
    "lore": "You are an initiate, on the path to completing the trials of the five gods in the hope of earning a glorified death in the final Trial of Zeal. Some combination of your natural aptitude, your crop's needs, and your teachers' assessment while you were an acolyte led you to focus your training in one particular area of specialization—hand-to-hand combat, long-range combat, or spellcasting. But only a well-rounded initiate can be called truly worthy of the afterlife. If you are a hand-to-hand specialist, consider the barbarian, fighter, monk, paladin, or rogue classes. As a long-range combat specialist, you might be a fighter, a ranger, or a rogue. If you are a spellcasting specialist, you might be a bard, sorcerer, or wizard. And beyond this initial choice, you might consider multiclassing or using feats to round out your skills in all three areas.",
    "loreSource": "PSA:backgroundFluff"
  },
  "initiate-dissenter|PSA": {
    "name": "Initiate (Dissenter)",
    "source": "PSA",
    "lore": "Even in the carefully constructed and curated city-state of a carefully ordered city-state, and in the presence of the five gods, some people rebel against the doctrines of the God-Pharaoh. They don't challenge the existence of the gods, of course, for those gods are visible nearly every day in the streets of the city. Nor do they question the fact of life after death, which is plain to see in the anointed mummies that surround them, as well as the marauding mummies outside the Hekma. Rather, these dissenters simply refuse to follow the ordained course of life that leads to the glorious afterlife. Some dissenters are spurred by fear, not wanting to subject themselves to a violent death in the trials (or in training for the trials). Some are moved by conscience, unwilling to kill their crop-mates in the trials. For while they cannot deny that the gods exist, they can deny that the gods are just—and can fight to prove that the dictates of an unjust god need not be obeyed. Some believe that one god (probably Bontu) has corrupted the process of the trials and the path to the afterlife. Others correctly intuit that the God-Pharaoh did not actually have the people's best interests in mind when he ordered their society.",
    "loreSource": "PSA:backgroundFluff"
  },
  "inquisitive|EFA": {
    "name": "Inquisitive",
    "source": "EFA",
    "lore": "You have honed your talents of investigation and deduction—fueled by a boundless curiosity—to explore mysteries, find missing people, recover stolen goods, unearth corruption and conspiracies, and solve crimes. As an inquisitive, you might have pursued freelance work, signed on with an inquisitive agency (perhaps one licensed by a dragonmarked house such as Medani or Tharashk), reported for a broadsheet, or worked for a police force.",
    "loreSource": "EFA:backgroundFluff"
  },
  "inquisitor|PSI": {
    "name": "Inquisitor",
    "source": "PSI",
    "lore": "Your life as Inquisitor shaped the habits, relationships, and hard-earned experience you carried into adventuring. Decide who taught you, what ended that chapter of your life, and which person, place, or obligation still connects you to it.",
    "loreSource": "campaign-neutral-fallback"
  },
  "investigator|RHW": {
    "name": "Investigator",
    "source": "RHW",
    "lore": "You relentlessly seek the truth. Perhaps you witnessed something remarkable or terrible and now desire to unravel its mystery, or maybe you're motivated by universal justice and honesty. Whether the cases you're embroiled in are local crimes or eldritch conspiracies, you're driven to reveal what others would keep hidden.",
    "loreSource": "RHW:backgroundFluff"
  },
  "izzet-engineer|GGR": {
    "name": "Izzet Engineer",
    "source": "GGR",
    "lore": "Armed with an inventive intellect, a love of magical technology, and an unquenchable energy, you are an enthusiastic participant in the research work of the Izzet League. Though you're likely to begin your career as a mere attendant, you can aspire to become a skilled mage or alchemist, a laboratory supervisor, or even a flamethrower-wielding scorchbringer tasked with defending Izzet laboratories. The Izzet are obsessive, brilliant, inspired, and an unpredictable force of chaos in a vast metropolis, and you epitomize all of those qualities.",
    "loreSource": "GGR:backgroundFluff"
  },
  "knight-of-solamnia|DSOTDQ": {
    "name": "Knight of Solamnia",
    "source": "DSotDQ",
    "lore": "You have trained to be a valorous warrior known as a Knight of Solamnia. Strict rules guide your every action, and you work to uphold them as you strive to defend the weak and oppose evil. Your honor is as important to you as your life.",
    "loreSource": "DSotDQ:backgroundFluff"
  },
  "knight-of-the-gauntlet|FRHOF": {
    "name": "Knight of the Gauntlet",
    "source": "FRHoF",
    "lore": "Not all who answer the call of a higher power are content to pore over scripture in a stuffy temple apse. You chose the path of the holy warrior by joining the Order of the Gauntlet. As a knight of the Gauntlet, you exercise righteous scorn for the forces of evil, unswerving camaraderie for your siblings in arms, and heartfelt compassion for the survivors of war. With weapon and holy symbol in hand, you've sworn not to rest until the light of justice has vanquished the shadow of chaos across the wider world.",
    "loreSource": "FRHoF:backgroundFluff"
  },
  "knight-of-the-order|SCAG": {
    "name": "Knight of the Order",
    "source": "SCAG",
    "lore": "Life as Knight of the Order placed you inside a disciplined martial tradition with its own duties, comrades, and scars. Decide which campaign defined you and whether your former allegiance is a source of pride, regret, or unfinished business.",
    "loreSource": "campaign-neutral-fallback"
  },
  "lords-alliance-vassal|FRHOF": {
    "name": "Lords' Alliance Vassal",
    "source": "FRHoF",
    "lore": "You were raised around status, obligation, reputation, and the long memory of an influential family or court. Your name and manners can open doors, but they also bind you to inherited duties, ambitious relatives, old alliances, and enemies you did not choose.",
    "loreSource": "campaign-neutral-fallback"
  },
  "lorehold-student|SCC": {
    "name": "Lorehold Student",
    "source": "SCC",
    "lore": "You have spent your youth preparing to be a student of Lorehold College, reading every book on the college's recommended reading list for prospective students. Your academic passions are in the broad field of history. You might dream of using magic to contact great historical figures or your own ancestors or of recreating the mighty magic of a distant age.",
    "loreSource": "SCC:backgroundFluff"
  },
  "lorwyn-expert|LFL": {
    "name": "Lorwyn Expert",
    "source": "LFL",
    "lore": "You hail from Lorwyn, a land of eternal sunshine, or you have studied the place with great intensity. You consider the majestic creature Eirdu the living embodiment of the sun, and you love embarking on whimsical adventures. You hold your loved ones close, even if only emotionally, for you've seen some venture into Shadowmoor or beyond and become faded versions of themselves. You're nevertheless courageous and always long for new experiences.",
    "loreSource": "LFL:backgroundFluff"
  },
  "luxonborn-acolyte|EGW": {
    "name": "Luxonborn (Acolyte)",
    "source": "EGW",
    "lore": "Every acolyte is a servant of some god. But you serve the Luxon, a being that you believe transcends godhood and created the cosmos. No mere priest, you are a student of potential, for the Luxon is potentiality incarnate. Your Shelter of the Faithful feature applies to all who venerate the Luxon, and to all who practice the art of dunamancy that the Luxon bestowed upon the world.",
    "loreSource": "EGW:backgroundFluff"
  },
  "mage-of-high-sorcery|DSOTDQ": {
    "name": "Mage of High Sorcery",
    "source": "DSotDQ",
    "lore": "Your talent for magic came to the attention of the Mages of High Sorcery, an organization of spellcasters that studies magic and prevents its misuse. You've trained among the Mages, but whether you'll face the dangerous test required to become a full member of the group remains to be determined. Your passion for studying magic has likely already predisposed you toward one of the organization's three orders: the benevolent Order of the White Robes, the balance-pursuing Order of the Red Robes, or the ruthless Order of the Black Robes. In the world of Krynn, many refer to the Mages of High Sorcery as the Wizards of High Sorcery. The organization accepts more than wizards, though, with sorcerers, warlocks, and other spellcasters included among their ranks.",
    "loreSource": "DSotDQ:backgroundFluff"
  },
  "marine|GOS": {
    "name": "Marine",
    "source": "GoS",
    "lore": "You were trained for battle on sandy beaches and rocky shores. You have launched midnight raids from swift ships whose names evoke terror in the hearts of your adversaries. The water is your second home, the rain your shelter, and the crashing waves your battle cry.",
    "loreSource": "GoS:backgroundFluff"
  },
  "mercenary-veteran|SCAG": {
    "name": "Mercenary Veteran",
    "source": "SCAG",
    "lore": "As a sell-sword who fought battles for coin, you're well acquainted with risking life and limb for a chance at a share of treasure. Now, you look forward to fighting foes and reaping even greater rewards as an adventurer. Your experience makes you familiar with the ins and outs of mercenary life, and you likely have harrowing stories of events on the battlefield. You might have served with a large outfit such as the Zhentarim or the soldiers of an island stronghold, or a smaller band of sell-swords, maybe even more than one. (See the \"Mercenaries of the North\" sidebar for a collection of possibilities.) Now you're looking for something else, perhaps greater reward for the risks you take, or the freedom to choose your own activities. For whatever reason, you're leaving behind the life of a soldier for hire, but your skills are undeniably suited for battle, so now you fight on in a different way.",
    "loreSource": "SCAG:backgroundFluff"
  },
  "merchant|XPHB": {
    "name": "Merchant",
    "source": "XPHB",
    "lore": "You were apprenticed to a trader, caravan master, or shopkeeper, learning the fundamentals of commerce. You traveled broadly, and you earned a living by buying and selling the raw materials artisans need to practice their craft or finished works from such crafters. You might have transported goods from one place to another (by ship, wagon, or caravan) or bought them from traveling traders and sold them in your own shop.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "mist-wanderer|RHW": {
    "name": "Mist Wanderer",
    "source": "RHW",
    "lore": "You once knew your home. But one day, the Mists rose and drew you into a Domain of Dread. Ever since, you have wandered between domains, braving the mercurial Mists as you search for a way home. Your time in these cursed realms has changed you, yet you find solace in communities of fellow wanderers throughout the Mists.",
    "loreSource": "RHW:backgroundFluff"
  },
  "moonwell-pilgrim|FRHOF": {
    "name": "Moonwell Pilgrim",
    "source": "FRHoF",
    "lore": "Your life as Moonwell Pilgrim shaped the habits, relationships, and hard-earned experience you carried into adventuring. Decide who taught you, what ended that chapter of your life, and which person, place, or obligation still connects you to it.",
    "loreSource": "campaign-neutral-fallback"
  },
  "mulhorandi-tomb-raider|FRHOF": {
    "name": "Mulhorandi Tomb Raider",
    "source": "FRHoF",
    "lore": "You grew up in a land of living god-kings, and as a child you were told countless stories of ancient empires and buried cities. In these tales, an ancient desert kingdom was a land overflowing with forgotten riches—priceless treasures awaiting anyone cunning and brave enough to seek them out. You've taken it upon yourself to explore your homeland's crypts, tombs, and pyramids to reclaim your people's relics.",
    "loreSource": "FRHoF:backgroundFluff"
  },
  "myriad-operative-criminal|EGW": {
    "name": "Myriad Operative (Criminal)",
    "source": "EGW",
    "lore": "Most criminals in the wider world are petty thieves and cutpurses who operate out of desperation. You, however, are a criminal of a higher caliber. You are a member of the Myriad, the greatest crime syndicate to ever grace the face of Exandria. You have a network of criminal contacts and allies to help you in your crimes—but you also have rivals and superiors that would gladly throw you to the wolves to save their own skins. The Myriad has bases of operation in every major city outside Eastern Wynandir, even if those bases are made up of only two or three members. Wherever you find the Myriad, you can find temporary shelter from the law—for a price.",
    "loreSource": "EGW:backgroundFluff"
  },
  "mythalkeeper|FRHOF": {
    "name": "Mythalkeeper",
    "source": "FRHoF",
    "lore": "Your life as Mythalkeeper shaped the habits, relationships, and hard-earned experience you carried into adventuring. Decide who taught you, what ended that chapter of your life, and which person, place, or obligation still connects you to it.",
    "loreSource": "campaign-neutral-fallback"
  },
  "noble|XPHB": {
    "name": "Noble",
    "source": "XPHB",
    "lore": "You were raised in a castle, surrounded by wealth, power, and privilege. Your family of minor aristocrats ensured that you received a first-class education, some of which you appreciated and some of which you resented. Your time in the castle, especially the many hours you spent observing your family at court, also taught you a great deal about leadership.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "orzhov-representative|GGR": {
    "name": "Orzhov Representative",
    "source": "GGR",
    "lore": "The prospect of immense wealth is the promise of membership in the Orzhov Syndicate. All of the guild's endeavors channel wealth from metropolitan society into the ranks of the Orzhov—and concentrates the spoils at the top of the hierarchy. As a functionary in that system, your best hope is to claim as much as possible of the money that passes through your hands on its way up, so that you can work your way into a more prominent position. Regardless of your past and the wealth of your family, your initial status with the guild is near the bottom, until you have proven your value.",
    "loreSource": "GGR:backgroundFluff"
  },
  "outlander|PHB": {
    "name": "Outlander",
    "source": "PHB",
    "lore": "You grew up in the wilds, far from civilization and the comforts of town and technology. You've witnessed the migration of herds larger than forests, survived weather more extreme than any city-dweller could comprehend, and enjoyed the solitude of being the only thinking creature for miles in any direction. The wilds are in your blood, whether you were a nomad, an explorer, a recluse, a hunter-gatherer, or even a marauder. Even in places where you don't know the specific features of the terrain, you know the ways of the wild.",
    "loreSource": "PHB:backgroundFluff"
  },
  "plaintiff|AI": {
    "name": "Plaintiff",
    "source": "AI",
    "lore": "Sure, accidents happen. But they seem to happen an awful lot when Acquisitions Incorporated operatives are on the scene. Naturally, nothing ever happens when there are no witnesses left behind. But sometimes one casualty is left a little less than dead, just waiting to discover what a lucky break that accident actually was. You were a victim of a legal incident that was ostensibly the fault of Acquisitions Incorporated. At least that's what the local magistrate said. But before a final ruling could be handed down, Acquisitions Incorporated offered you a job! Don't know how to swing a sword? They promised to teach you! Think you have what it takes to sling spells? They've got masters who'll have you throwing fire in no time!",
    "loreSource": "AI:backgroundFluff"
  },
  "planar-philosopher|SATO": {
    "name": "Planar Philosopher",
    "source": "SatO",
    "lore": "You subscribe to a philosophy that seeks to understand the nature of the planes or some hidden truth of the multiverse. You draw strength from your conviction and, perhaps, a network of like-minded thinkers, such as the factions of a planar crossroads city (summarized below). In your travels, you explore the depths of your understanding and spread your philosophy wherever you go.",
    "loreSource": "SatO:backgroundFluff"
  },
  "prismari-student|SCC": {
    "name": "Prismari Student",
    "source": "SCC",
    "lore": "You are an artist, and you have been preparing to hone your craft according to the traditions of Prismari College. Whatever your medium—sculpture, dance, paint, music, drama, architecture, or any other field—you have grand visions of bringing your art to life in a fusion of magic and creativity.",
    "loreSource": "SCC:backgroundFluff"
  },
  "purple-dragon-squire|FRHOF": {
    "name": "Purple Dragon Squire",
    "source": "FRHoF",
    "lore": "You've pledged your life to the safety of a well-ordered kingdom and sought admission to that realm's order of elite warriors: the Purple Dragon Knights. But before you have the chance to join the ranks officially, you must first serve as a knight's squire. You've found a liege willing to take you on and teach you the order's ways. Will you uphold the Purple Dragon Knights' ideals of glory, honor, and strength and prove yourself worthy of knighthood?",
    "loreSource": "FRHoF:backgroundFluff"
  },
  "quandrix-student|SCC": {
    "name": "Quandrix Student",
    "source": "SCC",
    "lore": "In preparation to become a student of Quandrix College, you have spent years working through the college's math problems for prospective students. Your interests concentrate on the mathematical principles and patterns found in the natural world. You might lean more toward mathematics or physics, or you delve into more abstract studies of metaphysics, arcana, or logic.",
    "loreSource": "SCC:backgroundFluff"
  },
  "rakdos-cultist|GGR": {
    "name": "Rakdos Cultist",
    "source": "GGR",
    "lore": "You're an entertainer at heart, a performer with a flair for the dramatic and a love of the spotlight. You've spent years honing your craft, mastering a demanding set of skills so you can perform them with panache and make them look easy. The wild applause, the screams of the crowds, the mayhem and terror spreading into the streets—this is what you live for. You're also a member of a cult devoted to an ancient demon who delights in violence and chaos. It just so happens that Rakdos loves a good show, and your highest aspiration is to please the Defiler, the Lord of Riots, with your own performance.",
    "loreSource": "GGR:backgroundFluff"
  },
  "rashemi-wanderer|FRHOF": {
    "name": "Rashemi Wanderer",
    "source": "FRHoF",
    "lore": "You spent years wandering the highlands of a rugged eastern homeland, a dangerous windswept heath that's dotted with ancient obelisks enchanted to imprison Fiends and home to dragons, gnolls, and other deadly creatures. Friendships are hard to find in such an isolated land, and you've learned to keep strangers at a distance.",
    "loreSource": "FRHoF:backgroundFluff"
  },
  "revelry-pirate-sailor|EGW": {
    "name": "Revelry Pirate (Sailor)",
    "source": "EGW",
    "lore": "Surviving as Revelry Pirate (Sailor) required nerve, useful contacts, and a flexible relationship with authority. Someone from that life may still consider you a partner, a debtor, a rival, or a loose end.",
    "loreSource": "campaign-neutral-fallback"
  },
  "rewarded|BMT": {
    "name": "Rewarded",
    "source": "BMT",
    "lore": "You were living a difficult life before your destiny suddenly changed through a miraculous turn of good fortune. Perhaps a benevolent deity gave you precisely what you most desired. You might have stumbled across a Deck of Many Things and drawn a card with a potent, positive effect. Or maybe you inherited a modest fortune from a distant relative you didn't know you had. Regardless, you left the daily miseries of your old life behind in favor of a life of adventure and excitement. Your old debts have been paid, responsibilities you thought inescapable are behind you, or you suddenly possess rare and unusual skills unknown to ordinary folk.",
    "loreSource": "BMT:backgroundFluff"
  },
  "rival-intern|AI": {
    "name": "Rival Intern",
    "source": "AI",
    "lore": "You were an intern at a rival of Acquisitions Incorporated, and you gained a healthy respect for not just the job and the franchising opportunities, but for the ruthless and efficient way Acquisitions Incorporated goes about its business. Why deal with the rest, when you can work for the best? Perhaps the rival did not treat you as well as you were hoping, or you washed out of that organization. Maybe you hope to leverage the knowledge you gained there for an advantage at Acquisitions Incorporated. Either way, you're now bringing your talents to the company, ready to put your skills to use.",
    "loreSource": "AI:backgroundFluff"
  },
  "ruined|BMT": {
    "name": "Ruined",
    "source": "BMT",
    "lore": "Everything was going so well! You had a life of luxury, love, and comfort when you suddenly lost it all. Perhaps you were framed for crimes you didn't commit and lost your reputation, fortune, and career. Maybe a rampaging dragon or another monster wiped out everything you had in a single calamitous afternoon. Or you might have sought out a Deck of Many Things, hoping to make your successful life even more glorious—only to draw a destructive card that changed your destiny forever. Your desperation has driven you to the career of adventurer. You don't seek out dark dungeons and their monstrous inhabitants for excitement and glory; you do it because every other path is closed to you. But you have risen high on fortune's wheel once before, and with luck and fortitude, you could do so again.",
    "loreSource": "BMT:backgroundFluff"
  },
  "rune-carver|BGG": {
    "name": "Rune Carver",
    "source": "BGG",
    "lore": "What we call rune magic is the palest imitation of Annam's creative work. He shaped worlds from the primal elements; we struggle to bind the merest scraps of elemental power into the mystic shapes of our runes. You've dedicated your life to studying runecraft. Whether you were taught by a master rune carver or learned by poring over ancient engravings, you can tap into the supernatural power held within runes.",
    "loreSource": "BGG:backgroundFluff"
  },
  "sage|XPHB": {
    "name": "Sage",
    "source": "XPHB",
    "lore": "You spent your formative years traveling between manors and monasteries, performing various odd jobs and services in exchange for access to their libraries. You whiled away many a long evening studying books and scrolls, learning the lore of the multiverse—even the rudiments of magic—and your mind yearns for more.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "sailor|XPHB": {
    "name": "Sailor",
    "source": "XPHB",
    "lore": "You lived as a seafarer, wind at your back and decks swaying beneath your feet. You've perched on barstools in more ports of call than you can remember, faced mighty storms, and swapped stories with folk who live beneath the waves.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "scribe|XPHB": {
    "name": "Scribe",
    "source": "XPHB",
    "lore": "You spent formative years in a scriptorium, a monastery dedicated to the preservation of knowledge, or a government agency, where you learned to write with a clear hand and produce finely written texts. Perhaps you scribed government documents or copied tomes of literature. You might have some skill as a writer of poetry, narrative, or scholarly research. Above all, you have a careful attention to detail, helping you avoid introducing mistakes to the documents you copy and create.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "selesnya-initiate|GGR": {
    "name": "Selesnya Initiate",
    "source": "GGR",
    "lore": "You are a member of a blessed community, built on the ideals of harmony. Here, nature and civilization coexist peacefully, living and growing in accordance with the will of the Worldsoul, Mat'Selesnya. As a member of the Selesnya Conclave, you are surrounded by people and other creatures who share your worldview and your longing for deeper spiritual communion with the world, and you have a fervent desire to share the joy you have experienced with a vast metropolis. Along with the rest of the conclave, you are committed to resisting the ambitions of the other guilds—with military force if necessary.",
    "loreSource": "GGR:backgroundFluff"
  },
  "shadowmasters-exile|FRHOF": {
    "name": "Shadowmasters Exile",
    "source": "FRHoF",
    "lore": "You trained your whole life to become a member of the Shadowmasters, the mysterious thieves' guild that controls the realm of an eastern trade land from behind the scenes. Stealth and quick reflexes were just the start of your Shadowmaster education; you also needed to hone your ruthlessness to ensure the safety of the guild's secrets. But one wrong move led to your expulsion from the order. Now you must walk your own path.",
    "loreSource": "FRHoF:backgroundFluff"
  },
  "shadowmoor-expert|LFL": {
    "name": "Shadowmoor Expert",
    "source": "LFL",
    "lore": "You are from Shadowmoor or have studied it for years. It's a gloomy, chaotic place perpetually lit by pale moonlight. You might survive Shadowmoor's merciless conditions thanks to your wit and cunning, or you might keep threats at bay with your brawn and bravery. Regardless of where you tread, you keenly understand that friendship is a rare commodity. You believe that knowing who to trust and who to keep at arm's length isn't just practical—it's often a matter of life or death.",
    "loreSource": "LFL:backgroundFluff"
  },
  "shipwright|GOS": {
    "name": "Shipwright",
    "source": "GoS",
    "lore": "You have sailed into war on the decks of great ships, patching their hulls with soup bowls and prayers. You once helped build a fishing vessel that single-handedly saved a town from starvation. You have seen a majestic prow in your dreams that you have not been able to replicate in wood. Since childhood, you have loved the water and have been captivated by the many vessels that travel on it.",
    "loreSource": "GoS:backgroundFluff"
  },
  "silverquill-student|SCC": {
    "name": "Silverquill Student",
    "source": "SCC",
    "lore": "You have spent years practicing your writing and oration in the hope of becoming a student of Silverquill College. Your studies focus on language, literature, and the power of words, both magical and otherwise. The metaphorical power of words to illuminate or conceal is joined with the literal ability of magic to do the same in your academic pursuits.",
    "loreSource": "SCC:backgroundFluff"
  },
  "simic-scientist|GGR": {
    "name": "Simic Scientist",
    "source": "GGR",
    "lore": "Imagine a perfect world: one in which nature and civilization exist in harmony, adapted to each other; one in which life is shaped to match its environment and the environment is shaped to match life. That's the world you have been trying to grow in the laboratories of the Simic Combine. Nature is all about adaptation, evolution, and balance—but for it to keep up with the pace of advancing civilization, nature needs some help from biomancers and terraformers. If, along the way, you happen to create super-soldiers and mutant monsters that can bolster the combine's defenses against the schemes and ambitions of the other guilds, so much the better.",
    "loreSource": "GGR:backgroundFluff"
  },
  "smuggler|GOS": {
    "name": "Smuggler",
    "source": "GoS",
    "lore": "On a rickety barge, you carried a hundred longswords in fish barrels right past the dock master's oblivious lackeys. You have paddled a riverboat filled with stolen elven wine under the gaze of the moon and sold it for twice its value in the morning. In your more charitable times, you have transported innocents out of war zones or helped guide herd animals to safety on the banks of a burning river.",
    "loreSource": "GoS:backgroundFluff"
  },
  "soldier|XPHB": {
    "name": "Soldier",
    "source": "XPHB",
    "lore": "You began training for war as soon as you reached adulthood and carry precious few memories of life before you took up arms. Battle is in your blood. Sometimes you catch yourself reflexively performing the basic fighting exercises you learned first. Eventually, you put that training to use on the battlefield, protecting the realm by waging war.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "spellfire-initiate|FRHOF": {
    "name": "Spellfire Initiate",
    "source": "FRHoF",
    "lore": "You bear the gift of spellfire: a rare form of magic that channels the raw power of the Weave. Wielding spellfire takes a heavy toll on the body. You've trained both mind and body to efficiently wield this sacred power.",
    "loreSource": "FRHoF:backgroundFluff"
  },
  "spirit-medium|RHW": {
    "name": "Spirit Medium",
    "source": "RHW",
    "lore": "Through strange rituals and fateful encounters, you've discovered that you bear a unique connection to the spirits of the dead and damned. Your body is a conduit for such spirits, granting you prescient insight from beyond. But these spirits' intentions aren't always innocent, and their gifts come at a haunting cost.",
    "loreSource": "RHW:backgroundFluff"
  },
  "urban-bounty-hunter|SCAG": {
    "name": "Urban Bounty Hunter",
    "source": "SCAG",
    "lore": "Surviving as Urban Bounty Hunter required nerve, useful contacts, and a flexible relationship with authority. Someone from that life may still consider you a partner, a debtor, a rival, or a loose end.",
    "loreSource": "campaign-neutral-fallback"
  },
  "urchin|PHB": {
    "name": "Urchin",
    "source": "PHB",
    "lore": "You grew up on the streets alone, orphaned, and poor. You had no one to watch over you or to provide for you, so you learned to provide for yourself. You fought fiercely over food and kept a constant watch out for other desperate souls who might steal from you. You slept on rooftops and in alleyways, exposed to the elements, and endured sickness without the advantage of medicine or a place to recuperate. You've survived despite all odds, and did so through cunning, strength, speed, or some combination of each. You begin your adventuring career with enough money to live modestly but securely for at least ten days. How did you come by that money? What allowed you to break free of your desperate circumstances and embark on a better life?",
    "loreSource": "PHB:backgroundFluff"
  },
  "uthgardt-tribe-member|SCAG": {
    "name": "Uthgardt Tribe Member",
    "source": "SCAG",
    "lore": "Though you might have only recently arrived in civilized lands, you are no stranger to the values of cooperation and group effort when striving for supremacy. You learned these principles, and much more, as a member of an Uthgardt tribe. Your people have always tried to hold to the old ways. Tradition and taboo have kept the Uthgardt strong while the kingdoms of others have collapsed into chaos and ruin. But for the last few generations, some bands among the tribes were tempted to settle, make peace, trade, and even to build towns. Perhaps this is why Uthgar chose to raise up the totems among the people as living embodiments of his power. Perhaps they needed a reminder of who they were and from whence they came. The Chosen of Uthgar led bands back to the old ways, and most of your people abandoned the soft ways of civilization.",
    "loreSource": "SCAG:backgroundFluff"
  },
  "vampire-devotee|ABH": {
    "name": "Vampire Devotee",
    "source": "ABH",
    "lore": "You were in service to a vampire or a small group of vampires lairing together. The Undead drank your blood more times than you can count. You might have served willingly, perhaps with aspirations of one day becoming a vampire yourself. Or you might have been magically charmed and retain only a few muddled memories of your time as a vampire familiar. In either case, your time in the vampire den is over.",
    "loreSource": "ABH:backgroundFluff"
  },
  "vampire-survivor|ABH": {
    "name": "Vampire Survivor",
    "source": "ABH",
    "lore": "You witnessed or survived a vampire attack. You might have been directly involved in this confrontation, or perhaps you were frozen in terror by what you saw. Regardless, you remain vigilant for monster attacks and pride yourself on being ready for anything. No vampire will catch you or your allies by surprise again.",
    "loreSource": "ABH:backgroundFluff"
  },
  "variant-city-watch-investigator|SCAG": {
    "name": "Variant City Watch (Investigator)",
    "source": "SCAG",
    "lore": "Rarer than watch or patrol members are a community's investigators, who are responsible for solving crimes after the fact. Though such folk are seldom found in rural areas, nearly every settlement of decent size has at least one or two watch members who have the skill to investigate crime scenes and track down criminals. If your prior experience is as an investigator, you have proficiency in Investigation rather than Athletics.",
    "loreSource": "SCAG:backgroundFluff"
  },
  "variant-criminal-spy|PHB": {
    "name": "Variant Criminal (Spy)",
    "source": "PHB",
    "lore": "Although your capabilities are not much different from those of a burglar or smuggler, you learned and practiced them in a very different context: as an espionage agent. You might have been an officially sanctioned agent of the crown, or perhaps you sold the secrets you uncovered to the highest bidder.",
    "loreSource": "PHB:backgroundFluff"
  },
  "variant-entertainer-gladiator|PHB": {
    "name": "Variant Entertainer (Gladiator)",
    "source": "PHB",
    "lore": "A gladiator is as much an entertainer as any minstrel or circus performer, trained to make the arts of combat into a spectacle the crowd can enjoy. This kind of flashy combat is your entertainer routine, though you might also have some skills as a tumbler or actor. Using your By Popular Demand feature, you can find a place to perform in any place that features combat for entertainment–perhaps a gladiatorial arena or secret pit fighting club. You can replace the musical instrument in your equipment package with an inexpensive but unusual weapon, such as a trident or net.",
    "loreSource": "PHB:backgroundFluff"
  },
  "variant-guild-artisan-guild-merchant|PHB": {
    "name": "Variant Guild Artisan (Guild Merchant)",
    "source": "PHB",
    "lore": "Instead of an artisans' guild, you might belong to a guild of traders, caravan masters, or shopkeepers. You don't craft items yourself but earn a living by buying and selling the works of others (or the raw materials artisans need to practice their craft). Your guild might be a large merchant consortium (or family) with interests across the region. Perhaps you transported goods from one place to another, by ship, wagon, or caravan, or bought them from traveling traders and sold them in your own little shop. In some ways, the traveling merchant's life lends itself to adventure far more than the life of an artisan.",
    "loreSource": "PHB:backgroundFluff"
  },
  "variant-noble-knight|PHB": {
    "name": "Variant Noble (Knight)",
    "source": "PHB",
    "lore": "A knighthood is among the lowest noble titles in most societies, but it can be a path to higher status. If you wish to be a knight, choose the Retainers feature instead of the Position of Privilege feature. One of your commoner retainers is replaced by a noble who serves as your squire, aiding you in exchange for training on his or her own path to knighthood. Your two remaining retainers might include a groom to care for your horse and a servant who polishes your armor (and even helps you put it on). As an emblem of chivalry and the ideals of courtly love, you might include among your equipment a banner or other token from a noble lord or lady to whom you have given your heart–in a chaste sort of devotion. (This person could be your bond.)",
    "loreSource": "PHB:backgroundFluff"
  },
  "variant-noble-retainers|PHB": {
    "name": "Variant Noble (Retainers)",
    "source": "PHB",
    "lore": "You understand wealth, power, and privilege. You carry a noble title, and your family owns land, collects taxes, and wields significant political influence. You might be a pampered aristocrat unfamiliar with work or discomfort, a former merchant just elevated to the nobility, or a disinherited scoundrel with a disproportionate sense of entitlement. Or you could be an honest, hard-working landowner who cares deeply about the people who live and work on your land, keenly aware of your responsibility to them. Work with your DM to come up with an appropriate title and determine how much authority that title carries. A noble title doesn't stand on its own—it's connected to an entire family, and whatever title you hold, you will pass it down to your own children. Not only do you need to determine your noble title, but you should also work with the DM to describe your family and their influence on you.",
    "loreSource": "PHB:backgroundFluff"
  },
  "variant-sailor-pirate|PHB": {
    "name": "Variant Sailor (Pirate)",
    "source": "PHB",
    "lore": "You spent your youth under the sway of a dread pirate, a ruthless cutthroat who taught you how to survive in a world of sharks and savages. You've indulged in larceny on the high seas and sent more than one deserving soul to a briny grave. Fear and bloodshed are no strangers to you, and you've garnered a somewhat unsavory reputation in many a port town. If you decide that your sailing career involved piracy, you can choose the Bad Reputation feature instead of the Ship's Passage feature.",
    "loreSource": "PHB:backgroundFluff"
  },
  "vizier|PSA": {
    "name": "Vizier",
    "source": "PSA",
    "lore": "You are a vizier, a servant of your god. You perform tasks that are essential to facilitating the initiates' journey, so the gods reward you with entry into the afterlife with the God-Pharaoh's blessing. You hope to achieve the most honored status in the afterlife by being the best possible servant to your god. As a vizier, you can have any class, but you are especially likely to be a cleric, a druid (particularly if you serve Rhonas), or a paladin.",
    "loreSource": "PSA:backgroundFluff"
  },
  "vizier-dissenter|PSA": {
    "name": "Vizier (Dissenter)",
    "source": "PSA",
    "lore": "Even in the carefully constructed and curated city-state of a carefully ordered city-state, and in the presence of the five gods, some people rebel against the doctrines of the God-Pharaoh. They don't challenge the existence of the gods, of course, for those gods are visible nearly every day in the streets of the city. Nor do they question the fact of life after death, which is plain to see in the anointed mummies that surround them, as well as the marauding mummies outside the Hekma. Rather, these dissenters simply refuse to follow the ordained course of life that leads to the glorious afterlife. Some dissenters are spurred by fear, not wanting to subject themselves to a violent death in the trials (or in training for the trials). Some are moved by conscience, unwilling to kill their crop-mates in the trials. For while they cannot deny that the gods exist, they can deny that the gods are just—and can fight to prove that the dictates of an unjust god need not be obeyed. Some believe that one god (probably Bontu) has corrupted the process of the trials and the path to the afterlife. Others correctly intuit that the God-Pharaoh did not actually have the people's best interests in mind when he ordered their society.",
    "loreSource": "PSA:backgroundFluff"
  },
  "volstrucker-agent|EGW": {
    "name": "Volstrucker Agent",
    "source": "EGW",
    "lore": "Your years as Volstrucker Agent taught you to trade in trust, secrets, and carefully managed identities. Decide who recruited you, which loyalty matters most, and what information could still place you in danger.",
    "loreSource": "campaign-neutral-fallback"
  },
  "waterdhavian-noble|SCAG": {
    "name": "Waterdhavian Noble",
    "source": "SCAG",
    "lore": "You were raised around status, obligation, reputation, and the long memory of an influential family or court. Your name and manners can open doors, but they also bind you to inherited duties, ambitious relatives, old alliances, and enemies you did not choose.",
    "loreSource": "campaign-neutral-fallback"
  },
  "wayfarer|XPHB": {
    "name": "Wayfarer",
    "source": "XPHB",
    "lore": "You grew up on the streets surrounded by similarly ill-fated castoffs, a few of them friends and a few of them rivals. You slept where you could and did odd jobs for food. At times, when the hunger became unbearable, you resorted to theft. Still, you never lost your pride and never abandoned hope. Fate is not yet finished with you.",
    "loreSource": "XPHB:backgroundFluff"
  },
  "wildspacer|AAG": {
    "name": "Wildspacer",
    "source": "AAG",
    "lore": "You were raised in the void of Wildspace—home to asteroid miners, moon farmers, and other hardy folk. Perhaps you grew up in a far-flung settlement such as a remote asteroid settlement, or you spent your early years on the crew of a spelljamming ship, performing helpful chores such as swabbing the deck, loading and offloading cargo, and scraping barnacles off the hull. Whatever your history, life in Wildspace has toughened you so well that you are as brave as a Space Hamster when it comes to facing the terrors and other challenges of the airless night.",
    "loreSource": "AAG:backgroundFluff"
  },
  "witchlight-hand|WBTW": {
    "name": "Witchlight Hand",
    "source": "WBtW",
    "lore": "You crept into the Witchlight Carnival as a child or youth and never looked back, earning a place among those who work behind the scenes to keep the carnival in business. As a hand, you work hard and party hard. The carnival has borne you to many fantastic worlds, circling back around to your home world once every eight years, but you know almost nothing about these worlds because you spend all your time in the carnival. You know the other hands well, but the carnival's owners—Mister Witch and Mister Light—remain mysterious to you even after all these years. Maybe you joined the carnival to escape a dismal life at home, or maybe you were enchanted by the idea of visiting new places or the dream of becoming one of the carnival's star attractions. Now that you're older, carnival life has lost some of its appeal. The daily routine has grown tedious, the cyclical nature of the carnival's journey monotonous. The carnival no longer fills your heart with a sense of wonder. Perhaps greater adventures await you beyond the carnival's gates.",
    "loreSource": "WBtW:backgroundFluff"
  },
  "witherbloom-student|SCC": {
    "name": "Witherbloom Student",
    "source": "SCC",
    "lore": "You filled your childhood with rudimentary alchemical experiments, all in the hope of becoming a student of Witherbloom College. The life sciences are the focus of your reading, which include biology and necromancy. Brewing strange concoctions with medicinal properties, exploring the anatomies of monsters, and cataloging swamp flora are the kinds of studies you might pursue at Witherbloom College.",
    "loreSource": "SCC:backgroundFluff"
  },
  "zhentarim-mercenary|FRHOF": {
    "name": "Zhentarim Mercenary",
    "source": "FRHoF",
    "lore": "Maybe you needed the money. Maybe you longed for a family, no matter how dubious. Or maybe you're just good at getting the job done by any means necessary. Whatever your reason, you enlisted with the Zhentarim, the most notorious mercenary guild in the Realms. Though the Zhentarim's leaders insist the organization is more like a family than a shadowy syndicate, few families exhibit as much dishonesty, nepotism, and corruption as this one. You've honed your cunning, reflexes, and blade to climb the guild's ranks.",
    "loreSource": "FRHoF:backgroundFluff"
  }
});
