export const safeText = (value) => String(value ?? "").trim();
export const normalized = (value) => safeText(value).toLowerCase().replace(/[’']/g, "").replace(/[^a-z0-9]+/g, " ").trim();
export const slug = (value) => normalized(value).replace(/\s+/g, "-");
export const unique = (values = []) => [...new Set((Array.isArray(values) ? values : []).filter(Boolean))];

export const WARLOCK_INVOCATION_PROGRESSION_XPHB = Object.freeze([1, 3, 3, 3, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10]);
export const WARLOCK_INVOCATION_PROGRESSION_PHB = Object.freeze([0, 2, 2, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8]);
export const BATTLE_MASTER_MANEUVER_PROGRESSION = Object.freeze([0, 0, 3, 3, 3, 3, 5, 5, 5, 7, 7, 7, 7, 7, 9, 9, 9, 9, 9, 9]);
export const SORCERER_METAMAGIC_PROGRESSION_XPHB = Object.freeze([0, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6]);
export const SORCERER_METAMAGIC_PROGRESSION_PHB = Object.freeze([0, 0, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4]);
export const ARTIFICER_PLAN_PROGRESSION_EFA = Object.freeze([0, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8]);
export const ARCANE_SHOT_PROGRESSION = Object.freeze([0, 0, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6]);
export const RUNE_KNIGHT_PROGRESSION = Object.freeze([0, 0, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5]);
export const FOUR_ELEMENTS_DISCIPLINE_PROGRESSION = Object.freeze([0, 0, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5]);

export const OPTION_SUMMARIES = Object.freeze({
  "agonizing blast": "Add Charisma to one known Warlock damage cantrip's damage rolls.",
  "armor of shadows": "Cast Mage Armor on yourself without spending a spell slot.",
  "ascendant step": "Cast Levitate on yourself without spending a spell slot.",
  "devils sight": "See normally in darkness, including magical darkness, to the feature's listed range.",
  "devouring blade": "Attack three times with your pact weapon when you take the Attack action.",
  "eldritch mind": "Gain advantage on Constitution saves made to maintain Concentration.",
  "eldritch smite": "Spend a Pact Magic slot after a pact-weapon hit for extra force damage and a knockdown.",
  "eldritch spear": "Increase the range of a chosen known Warlock damage cantrip.",
  "fiendish vigor": "Cast False Life on yourself without a spell slot and take the maximum result on its Temporary Hit Point die.",
  "gaze of two minds": "Perceive through a willing creature and cast from its space while maintaining the link.",
  "gift of the depths": "Gain a swimming speed, breathe underwater, and cast Water Breathing without a slot.",
  "gift of the protectors": "Record names in your tome so a recorded creature can avoid dropping to 0 Hit Points once.",
  "investment of the chain master": "Empower your familiar and command its attack with a Bonus Action.",
  "lessons of the first ones": "Gain an Origin feat for which you qualify. This invocation is repeatable.",
  "lifedrinker": "Your pact weapon deals extra necrotic, psychic, or radiant damage and can restore Hit Points.",
  "mask of many faces": "Cast Disguise Self without spending a spell slot.",
  "master of myriad forms": "Cast Alter Self without spending a spell slot.",
  "misty visions": "Cast Silent Image without spending a spell slot.",
  "one with shadows": "While you are in dim light or darkness, cast Invisibility on yourself without spending a spell slot.",
  "otherworldly leap": "Cast Jump on yourself without spending a spell slot.",
  "pact of the blade": "Create or bond a melee pact weapon, gain proficiency with it, and use Charisma for its attack and damage rolls.",
  "pact of the chain": "Cast Find Familiar without a spell slot, unlock special familiar forms, and let your familiar attack through your Attack action.",
  "pact of the tome": "Conjure a Book of Shadows after a rest and fill it with three cantrips and two level-1 ritual spells from any class.",
  "repelling blast": "Push a creature hit by a chosen Warlock damage cantrip.",
  "thirsting blade": "Attack twice with your pact weapon when you take the Attack action.",
  "visions of distant realms": "Cast Arcane Eye without spending a spell slot.",
  "whispers of the grave": "Cast Speak with Dead without spending a spell slot.",
  "witch sight": "See a creature's true form despite shapechanging or illusion within the feature's range.",
  "ambush": "Add a Superiority Die to a Stealth check or Initiative roll.",
  "bait and switch": "Swap places with a willing nearby creature and grant one of you an AC bonus.",
  "commanders strike": "Direct an ally to use its Reaction to make an attack.",
  "commanding presence": "Add a Superiority Die to selected Charisma checks.",
  "disarming attack": "Add damage and force the target to save or drop an object.",
  "distracting strike": "Add damage and give the next allied attacker advantage against the target.",
  "evasive footwork": "Add a Superiority Die to AC while moving.",
  "feinting attack": "Use a Bonus Action to gain advantage and add damage to your next attack.",
  "goading attack": "Add damage and hinder the target's attacks against creatures other than you.",
  "lunging attack": "Increase an attack's reach and add the Superiority Die to its damage.",
  "maneuvering attack": "Add damage and let an ally move with reduced opportunity-attack risk.",
  "menacing attack": "Add damage and frighten the target on a failed save.",
  "parry": "Use a Reaction and Superiority Die to reduce melee damage taken.",
  "precision attack": "Add a Superiority Die to an attack roll.",
  "pushing attack": "Add damage and push the target on a failed save.",
  "rally": "Use a Bonus Action to grant an ally Temporary Hit Points.",
  "riposte": "Use a Reaction to attack a creature that misses you in melee.",
  "sweeping attack": "Damage a second nearby creature after a melee weapon hit.",
  "tactical assessment": "Add a Superiority Die to selected Investigation, History, or Insight checks.",
  "trip attack": "Add damage and knock the target Prone on a failed save.",
  "careful spell": "Protect chosen creatures from the worst effects of one of your saving-throw spells.",
  "distant spell": "Increase a spell's range or give a touch spell a short range.",
  "empowered spell": "Reroll a limited number of a spell's damage dice.",
  "extended spell": "Extend a spell's duration and improve Concentration protection after casting it.",
  "heightened spell": "Impose disadvantage on one target's saves against the spell.",
  "quickened spell": "Change an eligible spell's casting time to a Bonus Action.",
  "seeking spell": "Reroll a missed spell attack.",
  "subtle spell": "Cast without verbal, somatic, or most material components.",
  "transmuted spell": "Change one listed elemental damage type to another listed type.",
  "twinned spell": "Increase the number of targets of an eligible spell.",
});


export const INVOCATION_PLAYER_GUIDES = Object.freeze({
  "agonizing blast": Object.freeze({ summary: "Choose one Warlock cantrip you know that deals damage. Add your Charisma modifier to that cantrip's damage rolls.", rules: Object.freeze(["The chosen spell must be a Warlock cantrip you know and it must deal damage.", "You can take this invocation more than once, but each copy must affect a different eligible cantrip."]) }),
  "armor of shadows": Object.freeze({ summary: "Cast Mage Armor on yourself without spending a spell slot.", rules: Object.freeze([]) }),
  "ascendant step": Object.freeze({ summary: "Cast Levitate on yourself without spending a spell slot.", rules: Object.freeze([]) }),
  "devils sight": Object.freeze({ summary: "See normally through dim light and darkness—magical or nonmagical—within 120 feet.", rules: Object.freeze([]) }),
  "devouring blade": Object.freeze({ summary: "Your Thirsting Blade Extra Attack improves to two extra attacks, letting you make three pact-weapon attacks with the Attack action.", rules: Object.freeze(["This improves the Extra Attack granted by Thirsting Blade; it does not create a separate Attack action."]) }),
  "eldritch mind": Object.freeze({ summary: "You have Advantage on Constitution saving throws made to maintain Concentration.", rules: Object.freeze([]) }),
  "eldritch smite": Object.freeze({ summary: "Once per turn after you hit with your pact weapon, spend a Pact Magic slot for extra Force damage and a possible knockdown.", rules: Object.freeze(["The extra damage is 1d8 Force plus another 1d8 for each level of the Pact Magic slot you spend.", "After the hit, you can also knock the target Prone if it is Huge or smaller."]) }),
  "eldritch spear": Object.freeze({ summary: "Choose a known Warlock damage cantrip with at least 10 feet of range. Its range increases by 30 feet for each Warlock level you have.", rules: Object.freeze(["You can take this invocation more than once, but each copy must affect a different eligible cantrip."]) }),
  "fiendish vigor": Object.freeze({ summary: "Cast False Life on yourself without a spell slot. When you cast it this way, use the highest possible result on its Temporary Hit Point die.", rules: Object.freeze([]) }),
  "gaze of two minds": Object.freeze({ summary: "Use a Bonus Action to link senses with a willing creature you touch, then maintain the link with later Bonus Actions.", rules: Object.freeze(["The creature must stay on the same plane as you. The link lasts until the end of your next turn unless you use another Bonus Action to extend it.", "While linked, you gain the creature's special senses.", "If you and the creature are within 60 feet of each other, you can cast a spell as though you were standing in either your space or its space."]) }),
  "gift of the depths": Object.freeze({ summary: "Breathe underwater and gain a Swim Speed equal to your Speed. You can also cast Water Breathing once without a spell slot.", rules: Object.freeze(["The free Water Breathing casting recharges when you finish a Long Rest."]) }),
  "gift of the protectors": Object.freeze({ summary: "Your Book of Shadows can protect creatures whose names are written in it from dropping to 0 Hit Points.", rules: Object.freeze(["With your permission, a creature can use an action to write its name in the book. The page can hold a number of names equal to your Charisma modifier, with a minimum of one.", "If a named creature would drop to 0 Hit Points without being killed outright, it drops to 1 Hit Point instead.", "Once that protection triggers, nobody listed on the page can benefit from it again until you finish a Long Rest.", "You can use a Magic action while touching the page to erase a name."]) }),
  "investment of the chain master": Object.freeze({ summary: "Your familiar gains stronger movement, combat, damage, saving-throw, and defensive options.", rules: Object.freeze(["When you cast Find Familiar, give the familiar either a 40-foot Fly Speed or a 40-foot Swim Speed.", "As a Bonus Action, you can command the familiar to take the Attack action.", "When it deals Bludgeoning, Piercing, or Slashing damage, you can change that damage to Necrotic or Radiant.", "If the familiar forces a saving throw, it uses your spell save DC.", "When the familiar takes damage, you can use your Reaction to give it Resistance to that damage."]) }),
  "lessons of the first ones": Object.freeze({ summary: "Gain one Origin feat you qualify for.", rules: Object.freeze(["You can take this invocation more than once, but each copy must grant a different Origin feat."]) }),
  "lifedrinker": Object.freeze({ summary: "Once per turn on a pact-weapon hit, deal 1d6 extra Necrotic, Psychic, or Radiant damage and optionally spend a Hit Die to heal.", rules: Object.freeze(["Choose the extra damage type each time the feature applies.", "If you spend a Hit Die, roll it and regain Hit Points equal to the roll plus your Constitution modifier, with a minimum of 1 Hit Point."]) }),
  "mask of many faces": Object.freeze({ summary: "Cast Disguise Self without spending a spell slot.", rules: Object.freeze([]) }),
  "master of myriad forms": Object.freeze({ summary: "Cast Alter Self without spending a spell slot.", rules: Object.freeze([]) }),
  "misty visions": Object.freeze({ summary: "Cast Silent Image without spending a spell slot.", rules: Object.freeze([]) }),
  "one with shadows": Object.freeze({ summary: "While you are in dim light or darkness, cast Invisibility on yourself without spending a spell slot.", rules: Object.freeze([]) }),
  "otherworldly leap": Object.freeze({ summary: "Cast Jump on yourself without spending a spell slot.", rules: Object.freeze([]) }),
  "pact of the blade": Object.freeze({ summary: "As a Bonus Action, conjure a Simple or Martial melee pact weapon or bond with an eligible magic weapon you touch. You are proficient with it, can use it as a spellcasting focus, and can use Charisma for its attacks and damage.", rules: Object.freeze(["You cannot bond to a magic weapon if another creature is attuned to it or another Warlock is already bonded to it.", "When you attack with the bonded weapon, you can use Charisma instead of Strength or Dexterity for the attack and damage rolls.", "Each attack can deal the weapon's normal damage type or Necrotic, Psychic, or Radiant damage.", "The bond ends if you use this feature's Bonus Action again, if the weapon stays more than 5 feet from you for at least 1 minute, or if you die. A conjured weapon disappears when the bond ends."]) }),
  "pact of the chain": Object.freeze({ summary: "Learn Find Familiar and cast it as a Magic action without spending a spell slot. You can choose normal forms or special pact familiar forms.", rules: Object.freeze(["Special forms include Imp, Pseudodragon, Quasit, Skeleton, Slaad Tadpole, Sphinx of Wonder, Sprite, and Venomous Snake.", "When you take the Attack action, you can give up one of your attacks to let your familiar make one attack using its Reaction."]) }),
  "pact of the tome": Object.freeze({ summary: "After a Short or Long Rest, conjure a Book of Shadows containing three chosen cantrips and two chosen level-1 ritual spells from any class.", rules: Object.freeze(["The five spells must be spells you do not already have prepared. While the book is on you, those spells are prepared and count as Warlock spells for you.", "You can use the Book of Shadows as a spellcasting focus.", "The book disappears if you conjure another one with this feature or if you die."]) }),
  "repelling blast": Object.freeze({ summary: "Choose a known Warlock cantrip that uses an attack roll. When it hits a Large or smaller creature, push that creature up to 10 feet straight away from you.", rules: Object.freeze(["You can take this invocation more than once, but each copy must affect a different eligible cantrip."]) }),
  "thirsting blade": Object.freeze({ summary: "Your pact weapon gains Extra Attack: when you take the Attack action, you can attack twice with that weapon instead of once.", rules: Object.freeze([]) }),
  "visions of distant realms": Object.freeze({ summary: "Cast Arcane Eye without spending a spell slot.", rules: Object.freeze([]) }),
  "whispers of the grave": Object.freeze({ summary: "Cast Speak with Dead without spending a spell slot.", rules: Object.freeze([]) }),
  "witch sight": Object.freeze({ summary: "Gain Truesight out to 30 feet.", rules: Object.freeze([]) }),
});

export const INVOCATION_PREREQUISITES = Object.freeze({
  "agonizing blast": { minLevel: 2, followup: "Choose the affected known Warlock damage cantrip on the Spells step." },
  "ascendant step": { minLevel: 5 },
  "devils sight": { minLevel: 2 },
  "devouring blade": { minLevel: 12, requires: "Pact of the Blade" },
  "eldritch smite": { minLevel: 5, requires: "Pact of the Blade" },
  "eldritch spear": { minLevel: 2, followup: "Choose the affected known Warlock damage cantrip on the Spells step." },
  "fiendish vigor": { minLevel: 2 },
  "gift of the depths": { minLevel: 5 },
  "gift of the protectors": { minLevel: 9, requires: "Pact of the Tome" },
  "investment of the chain master": { minLevel: 5, requires: "Pact of the Chain" },
  "lessons of the first ones": { minLevel: 2, followup: "Choose the granted Origin feat in this choice card." },
  "lifedrinker": { minLevel: 9, requires: "Pact of the Blade" },
  "mask of many faces": { minLevel: 2 },
  "master of myriad forms": { minLevel: 5 },
  "one with shadows": { minLevel: 5 },
  "otherworldly leap": { minLevel: 2 },
  "repelling blast": { minLevel: 2, followup: "Choose the affected known Warlock damage cantrip on the Spells step." },
  "thirsting blade": { minLevel: 5, requires: "Pact of the Blade" },
  "visions of distant realms": { minLevel: 9 },
  "whispers of the grave": { minLevel: 7 },
  "witch sight": { minLevel: 15 },
});

export const CLASS_OPTION_PREREQUISITES = Object.freeze({
  "hill rune": { minLevel: 7 },
  "storm rune": { minLevel: 7 },
  "breath of winter": { minLevel: 17 },
  "clench of the north wind": { minLevel: 6 },
  "eternal mountain defense": { minLevel: 17 },
  "flames of the phoenix": { minLevel: 11 },
  "gong of the summit": { minLevel: 6 },
  "mist stance": { minLevel: 11 },
  "ride the wind": { minLevel: 11 },
  "river of hungry flame": { minLevel: 17 },
  "wave of rolling earth": { minLevel: 17 },
});
