begin;

alter table public.encounter_command_requests
  drop constraint if exists encounter_command_requests_command_type_check;
alter table public.encounter_command_requests
  add constraint encounter_command_requests_command_type_check
  check (command_type in ('move','end_turn','core_action','attack'));

alter table public.encounter_participants
  add column if not exists armor_class integer check (armor_class > 0),
  add column if not exists movement_bonus_ft integer not null default 0 check (movement_bonus_ft >= 0),
  add column if not exists disengaged boolean not null default false,
  add column if not exists dodging boolean not null default false;

create table if not exists public.encounter_combat_log (
  id bigint generated by default as identity primary key,
  encounter_id uuid not null references public.encounters(id) on delete cascade,
  round integer not null default 0,
  turn_index integer not null default 0,
  actor_participant_id uuid references public.encounter_participants(id) on delete set null,
  target_participant_id uuid references public.encounter_participants(id) on delete set null,
  event_type text not null,
  summary text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);
create index if not exists encounter_combat_log_encounter_idx on public.encounter_combat_log(encounter_id, id desc);
alter table public.encounter_combat_log enable row level security;
revoke all on public.encounter_combat_log from public, anon, authenticated;
grant select on public.encounter_combat_log to authenticated;
grant all on public.encounter_combat_log to service_role;
drop policy if exists encounter_combat_log_authenticated_read on public.encounter_combat_log;
create policy encounter_combat_log_authenticated_read on public.encounter_combat_log
for select to authenticated using (
  exists(select 1 from public.encounters e where e.id=encounter_id and e.status<>'archived')
  or public.is_admin(auth.uid())
);

do $backfill$
declare r record; v_dex integer; v_ac integer; v_hp integer;
begin
  for r in select p.id,p.character_id,cs.sheet from public.encounter_participants p left join public.character_sheets cs on cs.character_id=p.character_id loop
    begin v_dex := nullif(r.sheet#>>'{abilities,dex,score}','')::integer; exception when others then v_dex := null; end;
    begin v_ac := nullif(r.sheet->>'ac','')::integer; exception when others then v_ac := null; end;
    begin v_hp := coalesce(nullif(r.sheet->>'hp','')::integer,nullif(r.sheet->>'maxHp','')::integer); exception when others then v_hp := null; end;
    update public.encounter_participants
      set armor_class=coalesce(armor_class,v_ac,10+floor((coalesce(v_dex,10)-10)/2.0)::integer),
          current_hp=coalesce(current_hp,v_hp)
      where id=r.id;
  end loop;
end $backfill$;

create or replace function public.encounter_canonical_combat_snapshot_v1(p_character_id uuid)
returns jsonb
language plpgsql stable security definer
set search_path = pg_catalog, public, private, auth
as $function$
declare v_sheet jsonb; v_str integer:=10; v_dex integer:=10; v_prof integer:=2; v_ac integer; v_hp integer;
begin
  if p_character_id is null then return jsonb_build_object('str',10,'dex',10,'prof',2,'ac',10,'hp',1); end if;
  select cs.sheet into v_sheet from public.character_sheets cs where cs.character_id=p_character_id;
  if v_sheet is null then return jsonb_build_object('str',10,'dex',10,'prof',2,'ac',10,'hp',1); end if;
  begin v_str := coalesce(nullif(v_sheet#>>'{abilities,str,score}','')::integer,10); exception when others then v_str:=10; end;
  begin v_dex := coalesce(nullif(v_sheet#>>'{abilities,dex,score}','')::integer,10); exception when others then v_dex:=10; end;
  begin v_prof := coalesce(nullif(v_sheet->>'proficiencyBonus','')::integer,2); exception when others then v_prof:=2; end;
  begin v_ac := nullif(v_sheet->>'ac','')::integer; exception when others then v_ac:=null; end;
  begin v_hp := coalesce(nullif(v_sheet->>'hp','')::integer,nullif(v_sheet->>'maxHp','')::integer,1); exception when others then v_hp:=1; end;
  v_ac := coalesce(v_ac,10+floor((v_dex-10)/2.0)::integer);
  return jsonb_build_object('str',v_str,'dex',v_dex,'prof',v_prof,'ac',v_ac,'hp',v_hp);
end;$function$;
revoke all on function public.encounter_canonical_combat_snapshot_v1(uuid) from public, anon, authenticated;
grant execute on function public.encounter_canonical_combat_snapshot_v1(uuid) to service_role;

create or replace function public.admin_add_encounter_participant_v1(
  p_encounter_id uuid,p_character_id uuid,p_team text default 'neutral',p_q integer default 0,p_r integer default 0,p_controller_user_id uuid default null,p_state jsonb default '{}'::jsonb
) returns uuid language plpgsql security definer set search_path = pg_catalog, public, private, auth
as $function$
declare v_uid uuid:=auth.uid(); v_status text; v_character public.characters%rowtype; v_id uuid:=gen_random_uuid(); v_speed integer; v_snapshot jsonb;
begin
  if coalesce(auth.role(),'')<>'service_role' and (v_uid is null or not public.is_admin(v_uid)) then raise exception 'Admin required'; end if;
  if p_team not in ('players','allies','enemies','neutral') then raise exception 'Invalid participant team'; end if;
  select status into v_status from public.encounters where id=p_encounter_id for update;
  if not found then raise exception 'Encounter not found'; end if;
  if v_status not in ('draft','ready','initiative') then raise exception 'Participants can only be staged before active play'; end if;
  select * into v_character from public.characters where id=p_character_id;
  if not found then raise exception 'Character not found'; end if;
  if exists(select 1 from public.encounter_participants where encounter_id=p_encounter_id and character_id=p_character_id) then raise exception 'Character is already staged in this encounter'; end if;
  v_speed:=public.encounter_canonical_speed_ft_v1(p_character_id);
  v_snapshot:=public.encounter_canonical_combat_snapshot_v1(p_character_id);
  insert into public.encounter_participants(id,encounter_id,character_id,display_name,team,controller_user_id,q,r,sprite_asset_id,state,speed_ft,current_hp,armor_class)
  values(v_id,p_encounter_id,p_character_id,v_character.name,p_team,p_controller_user_id,p_q,p_r,v_character.visual_asset_id,coalesce(p_state,'{}'::jsonb),v_speed,(v_snapshot->>'hp')::integer,(v_snapshot->>'ac')::integer);
  update public.encounters set version=version+1,updated_at=timezone('utc',now()) where id=p_encounter_id;
  return v_id;
end;$function$;

create or replace function public.encounter_use_core_action_v1(p_participant_id uuid,p_action text,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public, private, auth
as $function$
declare v_uid uuid:=auth.uid(); v_role text:=coalesce(auth.role(),''); v_p public.encounter_participants%rowtype; v_e public.encounters%rowtype; v_existing public.encounter_command_requests%rowtype; v_inserted integer:=0; v_result jsonb;
begin
  if p_participant_id is null or p_request_id is null then raise exception 'Participant and request id are required'; end if;
  if p_action not in ('dash','disengage','dodge') then raise exception 'Unsupported core action'; end if;
  insert into public.encounter_command_requests(request_id,encounter_id,participant_id,command_type,requested_by)
  select p_request_id,p.encounter_id,p.id,'core_action',v_uid from public.encounter_participants p where p.id=p_participant_id on conflict(request_id) do nothing;
  get diagnostics v_inserted=row_count;
  if v_inserted=0 then select * into v_existing from public.encounter_command_requests where request_id=p_request_id; if not found or v_existing.command_type<>'core_action' or v_existing.participant_id<>p_participant_id then raise exception 'Request id is already used for another command'; end if; return coalesce(v_existing.result,jsonb_build_object('duplicate',true,'pending',true)); end if;
  select * into v_p from public.encounter_participants where id=p_participant_id for update; if not found then raise exception 'Participant not found'; end if;
  select * into v_e from public.encounters where id=v_p.encounter_id for update; if not found then raise exception 'Encounter not found'; end if;
  if v_e.status<>'active' or v_e.active_participant_id is distinct from v_p.id then raise exception 'It is not this participant''s active turn'; end if;
  if v_role<>'service_role' and not public.encounter_can_control_participant_v1(v_p.id) then raise exception 'Not authorized to control this participant'; end if;
  if v_p.is_defeated then raise exception 'Defeated participants cannot act'; end if;
  if not v_p.action_available then raise exception 'Action already spent'; end if;
  update public.encounter_participants set action_available=false,
    movement_bonus_ft=case when p_action='dash' then movement_bonus_ft+speed_ft else movement_bonus_ft end,
    disengaged=case when p_action='disengage' then true else disengaged end,
    dodging=case when p_action='dodge' then true else dodging end,
    updated_at=timezone('utc',now()) where id=v_p.id;
  insert into public.encounter_combat_log(encounter_id,round,turn_index,actor_participant_id,event_type,summary,detail)
  values(v_e.id,v_e.round,v_e.turn_index,v_p.id,'core_action',v_p.display_name||' used '||initcap(p_action)||'.',jsonb_build_object('action',p_action));
  update public.encounters set version=version+1,updated_at=timezone('utc',now()) where id=v_e.id;
  select jsonb_build_object('requestId',p_request_id,'action',p_action,'actionAvailable',action_available,'movementBonusFt',movement_bonus_ft,'disengaged',disengaged,'dodging',dodging) into v_result from public.encounter_participants where id=v_p.id;
  update public.encounter_command_requests set result=v_result where request_id=p_request_id;
  return v_result;
end;$function$;

create or replace function public.encounter_unarmed_strike_v1(p_attacker_id uuid,p_target_id uuid,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public, private, auth
as $function$
declare v_uid uuid:=auth.uid(); v_role text:=coalesce(auth.role(),''); v_a public.encounter_participants%rowtype; v_t public.encounter_participants%rowtype; v_e public.encounters%rowtype; v_existing public.encounter_command_requests%rowtype; v_inserted integer:=0; v_snap jsonb; v_str integer; v_prof integer; v_mod integer; v_roll1 integer; v_roll2 integer; v_roll integer; v_total integer; v_hit boolean; v_crit boolean; v_damage integer:=0; v_temp integer; v_hp integer; v_result jsonb; v_dist integer;
begin
  if p_attacker_id is null or p_target_id is null or p_request_id is null then raise exception 'Attacker, target and request id are required'; end if;
  if p_attacker_id=p_target_id then raise exception 'Attacker and target must differ'; end if;
  insert into public.encounter_command_requests(request_id,encounter_id,participant_id,command_type,requested_by)
  select p_request_id,p.encounter_id,p.id,'attack',v_uid from public.encounter_participants p where p.id=p_attacker_id on conflict(request_id) do nothing;
  get diagnostics v_inserted=row_count;
  if v_inserted=0 then select * into v_existing from public.encounter_command_requests where request_id=p_request_id; if not found or v_existing.command_type<>'attack' or v_existing.participant_id<>p_attacker_id then raise exception 'Request id is already used for another command'; end if; return coalesce(v_existing.result,jsonb_build_object('duplicate',true,'pending',true)); end if;
  select * into v_a from public.encounter_participants where id=p_attacker_id for update; if not found then raise exception 'Attacker not found'; end if;
  select * into v_t from public.encounter_participants where id=p_target_id and encounter_id=v_a.encounter_id for update; if not found then raise exception 'Target not found in this encounter'; end if;
  select * into v_e from public.encounters where id=v_a.encounter_id for update; if not found then raise exception 'Encounter not found'; end if;
  if v_e.status<>'active' or v_e.active_participant_id is distinct from v_a.id then raise exception 'It is not this participant''s active turn'; end if;
  if v_role<>'service_role' and not public.encounter_can_control_participant_v1(v_a.id) then raise exception 'Not authorized to control this participant'; end if;
  if v_a.is_defeated then raise exception 'Defeated participants cannot attack'; end if;
  if v_t.is_defeated then raise exception 'Target is already defeated'; end if;
  if not v_a.action_available then raise exception 'Action already spent'; end if;
  v_dist:=greatest(abs(v_t.q-v_a.q),abs(v_t.r-v_a.r),abs((v_t.q-v_a.q)+(v_t.r-v_a.r)));
  if v_dist>1 then raise exception 'Unarmed Strike target must be within 5 feet'; end if;
  v_snap:=public.encounter_canonical_combat_snapshot_v1(v_a.character_id); v_str:=(v_snap->>'str')::integer; v_prof:=(v_snap->>'prof')::integer; v_mod:=floor((v_str-10)/2.0)::integer;
  v_roll1:=floor(random()*20)::integer+1; v_roll2:=floor(random()*20)::integer+1; v_roll:=case when v_t.dodging then least(v_roll1,v_roll2) else v_roll1 end; v_total:=v_roll+v_mod+v_prof; v_crit:=v_roll=20; v_hit:=case when v_roll=1 then false when v_crit then true else v_total>=coalesce(v_t.armor_class,10) end;
  if v_hit then v_damage:=greatest(0,1+v_mod); end if;
  v_temp:=coalesce(v_t.temp_hp,0); v_hp:=coalesce(v_t.current_hp,1);
  if v_damage>0 then if v_temp>=v_damage then v_temp:=v_temp-v_damage; else v_hp:=greatest(0,v_hp-(v_damage-v_temp)); v_temp:=0; end if; end if;
  update public.encounter_participants set current_hp=v_hp,temp_hp=v_temp,is_defeated=(v_hp<=0),action_available=false,updated_at=timezone('utc',now()) where id=v_t.id;
  update public.encounter_participants set action_available=false,updated_at=timezone('utc',now()) where id=v_a.id;
  v_result:=jsonb_build_object('requestId',p_request_id,'attackerId',v_a.id,'targetId',v_t.id,'roll',v_roll,'secondRoll',case when v_t.dodging then v_roll2 else null end,'attackBonus',v_mod+v_prof,'total',v_total,'targetAc',coalesce(v_t.armor_class,10),'dodging',v_t.dodging,'hit',v_hit,'critical',v_crit,'damage',v_damage,'targetHp',v_hp,'targetTempHp',v_temp,'defeated',v_hp<=0);
  insert into public.encounter_combat_log(encounter_id,round,turn_index,actor_participant_id,target_participant_id,event_type,summary,detail)
  values(v_e.id,v_e.round,v_e.turn_index,v_a.id,v_t.id,'unarmed_strike',v_a.display_name||case when v_hit then ' hit ' else ' missed ' end||v_t.display_name||' with an Unarmed Strike.',v_result);
  update public.encounters set version=version+1,updated_at=timezone('utc',now()) where id=v_e.id;
  update public.encounter_command_requests set result=v_result where request_id=p_request_id;
  return v_result;
end;$function$;

create or replace function public.encounter_move_active_participant_v1(p_participant_id uuid,p_path jsonb,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public, private, auth
as $function$
declare v_uid uuid:=auth.uid(); v_role text:=coalesce(auth.role(),''); v_participant public.encounter_participants%rowtype; v_encounter public.encounters%rowtype; v_radius integer; v_inserted integer:=0; v_existing public.encounter_command_requests%rowtype; v_step jsonb; v_q integer; v_r integer; v_prev_q integer; v_prev_r integer; v_dq integer; v_dr integer; v_multiplier numeric; v_step_cost integer; v_spent integer; v_speed integer; v_allowance integer; v_facing text; v_result jsonb;
begin
  if p_participant_id is null or p_request_id is null then raise exception 'Participant and request id are required'; end if;
  if jsonb_typeof(p_path)<>'array' or jsonb_array_length(p_path)=0 then raise exception 'Movement path must contain at least one hex'; end if;
  insert into public.encounter_command_requests(request_id,encounter_id,participant_id,command_type,requested_by) select p_request_id,p.encounter_id,p.id,'move',v_uid from public.encounter_participants p where p.id=p_participant_id on conflict(request_id) do nothing; get diagnostics v_inserted=row_count;
  if v_inserted=0 then select * into v_existing from public.encounter_command_requests where request_id=p_request_id; if not found or v_existing.command_type<>'move' or v_existing.participant_id<>p_participant_id then raise exception 'Request id is already used for another command'; end if; return coalesce(v_existing.result,jsonb_build_object('duplicate',true,'pending',true)); end if;
  select * into v_participant from public.encounter_participants where id=p_participant_id for update; if not found then raise exception 'Participant not found'; end if;
  select * into v_encounter from public.encounters where id=v_participant.encounter_id for update; if not found then raise exception 'Encounter not found'; end if;
  if v_encounter.status<>'active' or v_encounter.active_participant_id is distinct from v_participant.id then raise exception 'It is not this participant''s active turn'; end if;
  if v_role<>'service_role' and not public.encounter_can_control_participant_v1(v_participant.id) then raise exception 'Not authorized to control this participant'; end if;
  select radius into v_radius from public.encounter_maps where id=v_encounter.map_id; v_speed:=public.encounter_canonical_speed_ft_v1(v_participant.character_id); v_allowance:=v_speed+coalesce(v_participant.movement_bonus_ft,0); v_spent:=coalesce(v_participant.movement_spent_ft,0); v_prev_q:=v_participant.q; v_prev_r:=v_participant.r;
  for v_step in select value from jsonb_array_elements(p_path) loop
    if coalesce(v_step->>'q','')!~'^-?[0-9]+$' or coalesce(v_step->>'r','')!~'^-?[0-9]+$' then raise exception 'Each path step must contain integer q and r'; end if;
    v_q:=(v_step->>'q')::integer; v_r:=(v_step->>'r')::integer; v_dq:=v_q-v_prev_q; v_dr:=v_r-v_prev_r;
    if greatest(abs(v_dq),abs(v_dr),abs(v_dq+v_dr))<>1 then raise exception 'Movement path must be contiguous'; end if;
    if greatest(abs(v_q),abs(v_r),abs(v_q+v_r))>v_radius then raise exception 'Movement leaves the encounter map'; end if;
    if exists(select 1 from public.encounter_hex_overrides h where h.map_id=v_encounter.map_id and h.q=v_q and h.r=v_r and h.terrain_type='blocked') or exists(select 1 from public.encounter_map_objects o where o.map_id=v_encounter.map_id and o.q=v_q and o.r=v_r and o.blocks_movement) then raise exception 'Movement path is blocked'; end if;
    if exists(select 1 from public.encounter_participants p where p.encounter_id=v_encounter.id and p.id<>v_participant.id and not p.is_defeated and p.q=v_q and p.r=v_r) then raise exception 'Movement path enters an occupied hex'; end if;
    select coalesce(h.movement_multiplier,1) into v_multiplier from public.encounter_hex_overrides h where h.map_id=v_encounter.map_id and h.q=v_q and h.r=v_r; v_step_cost:=ceil(5*coalesce(v_multiplier,1))::integer;
    if v_spent+v_step_cost>v_allowance then raise exception 'Movement exceeds remaining Speed'; end if;
    v_spent:=v_spent+v_step_cost; v_facing:=case when v_dq=1 and v_dr=0 then 'east' when v_dq=1 and v_dr=-1 then 'northeast' when v_dq=0 and v_dr=-1 then 'northwest' when v_dq=-1 and v_dr=0 then 'west' when v_dq=-1 and v_dr=1 then 'southwest' when v_dq=0 and v_dr=1 then 'southeast' else v_participant.facing end; v_prev_q:=v_q; v_prev_r:=v_r;
  end loop;
  update public.encounter_participants set q=v_prev_q,r=v_prev_r,facing=coalesce(v_facing,facing),movement_spent_ft=v_spent,speed_ft=v_speed,updated_at=timezone('utc',now()) where id=v_participant.id;
  update public.encounters set version=version+1,updated_at=timezone('utc',now()) where id=v_encounter.id;
  v_result:=jsonb_build_object('requestId',p_request_id,'participantId',v_participant.id,'q',v_prev_q,'r',v_prev_r,'speedFt',v_speed,'movementBonusFt',coalesce(v_participant.movement_bonus_ft,0),'movementSpentFt',v_spent,'remainingFt',greatest(0,v_allowance-v_spent)); update public.encounter_command_requests set result=v_result where request_id=p_request_id; return v_result;
end;$function$;

create or replace function public.encounter_end_turn_v1(p_participant_id uuid,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public, private, auth
as $function$
declare v_uid uuid:=auth.uid(); v_role text:=coalesce(auth.role(),''); v_p public.encounter_participants%rowtype; v_e public.encounters%rowtype; v_existing public.encounter_command_requests%rowtype; v_inserted integer:=0; v_current_pos integer; v_count integer; v_next_pos integer; v_next_id uuid; v_next_speed integer; v_round integer; v_result jsonb;
begin
  insert into public.encounter_command_requests(request_id,encounter_id,participant_id,command_type,requested_by) select p_request_id,p.encounter_id,p.id,'end_turn',v_uid from public.encounter_participants p where p.id=p_participant_id on conflict(request_id) do nothing; get diagnostics v_inserted=row_count;
  if v_inserted=0 then select * into v_existing from public.encounter_command_requests where request_id=p_request_id; if not found or v_existing.command_type<>'end_turn' then raise exception 'Request id is already used'; end if; return coalesce(v_existing.result,jsonb_build_object('duplicate',true)); end if;
  select * into v_p from public.encounter_participants where id=p_participant_id for update; if not found then raise exception 'Participant not found'; end if; select * into v_e from public.encounters where id=v_p.encounter_id for update;
  if v_e.status<>'active' or v_e.active_participant_id is distinct from v_p.id then raise exception 'It is not this participant''s active turn'; end if; if v_role<>'service_role' and not public.encounter_can_control_participant_v1(v_p.id) then raise exception 'Not authorized'; end if;
  with ordered as (select p.id,row_number() over(order by p.initiative desc nulls last,p.initiative_tiebreaker desc nulls last,p.created_at,p.id) rn,count(*) over() cnt from public.encounter_participants p where p.encounter_id=v_e.id and not p.is_defeated) select rn,cnt into v_current_pos,v_count from ordered where id=v_p.id;
  v_next_pos:=case when v_current_pos>=v_count then 1 else v_current_pos+1 end; with ordered as (select p.id,row_number() over(order by p.initiative desc nulls last,p.initiative_tiebreaker desc nulls last,p.created_at,p.id) rn from public.encounter_participants p where p.encounter_id=v_e.id and not p.is_defeated) select id into v_next_id from ordered where rn=v_next_pos;
  v_round:=case when v_next_pos=1 then greatest(1,v_e.round)+1 else greatest(1,v_e.round) end; select public.encounter_canonical_speed_ft_v1(character_id) into v_next_speed from public.encounter_participants where id=v_next_id;
  update public.encounter_participants set disengaged=false,movement_bonus_ft=0,updated_at=timezone('utc',now()) where id=v_p.id;
  update public.encounter_participants set movement_spent_ft=0,movement_bonus_ft=0,action_available=true,bonus_action_available=true,reaction_available=true,disengaged=false,dodging=false,speed_ft=v_next_speed,turn_started_at=timezone('utc',now()),updated_at=timezone('utc',now()) where id=v_next_id;
  update public.encounters set active_participant_id=v_next_id,round=v_round,turn_index=v_next_pos-1,version=version+1,updated_at=timezone('utc',now()) where id=v_e.id;
  v_result:=jsonb_build_object('requestId',p_request_id,'nextParticipantId',v_next_id,'round',v_round,'turnIndex',v_next_pos-1); update public.encounter_command_requests set result=v_result where request_id=p_request_id; return v_result;
end;$function$;

revoke all on function public.encounter_use_core_action_v1(uuid,text,uuid) from public, anon;
revoke all on function public.encounter_unarmed_strike_v1(uuid,uuid,uuid) from public, anon;
grant execute on function public.encounter_use_core_action_v1(uuid,text,uuid) to authenticated, service_role;
grant execute on function public.encounter_unarmed_strike_v1(uuid,uuid,uuid) to authenticated, service_role;

do $postconditions$ begin
  if has_table_privilege('authenticated','public.encounter_combat_log','INSERT') then raise exception 'authenticated must not write combat log'; end if;
  if not has_function_privilege('authenticated','public.encounter_use_core_action_v1(uuid,text,uuid)','EXECUTE') then raise exception 'core action RPC missing'; end if;
  if not has_function_privilege('authenticated','public.encounter_unarmed_strike_v1(uuid,uuid,uuid)','EXECUTE') then raise exception 'attack RPC missing'; end if;
  if has_function_privilege('anon','public.encounter_unarmed_strike_v1(uuid,uuid,uuid)','EXECUTE') then raise exception 'anon must not attack'; end if;
end $postconditions$;

commit;